GET http://localhost:3000/api/members

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
  "id":11,
  "name": "Alex",
  "team": "Engineering",
  "position": "Android Developer",
  "emailAddress": "zake@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2021/06/12",
  "birthday": "1995/09/27",
  "profileImage": "profile1.png"
}

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{
  "id": 1,
  "name": "Alex",
  "team": "engineering",
  "position": "IOS Developer",
  "emailAddress": "alex@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2018/12/10",
  "birthday": "1994/11/08",
  "profileImage": "profile1.png"
}

###
DELETE http://localhost:3000/api/members/3