import Head from "next/head";
import { Props } from "../types";

export default function Seo({ title } : Props) {
  return (
    <Head>
      <title>{`${title} | Next`}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
    </Head>
  );
}