POST https://learn.codeit.kr/api/avatar-service/users
Content-Type: application/json

{
  "name": "소드잇",
  "email": "thdbsgh3443@example.com",
  "password": "p@ssword"
}

###

POST https://learn.codeit.kr/api/avatar-service/auth/login
Content-Type: application/json

{
  "email": "thdbsgh3443@example.com",
  "password": "p@ssword"
}