import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createData, deleteData, getData, updateData } from '../../apis';

const inter = Inter({ subsets: ['latin'] });

type data = {
  "userId": Number,
  "id": Number,
  "title": String,
  "completed": Boolean
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode}) {
  await updateData(2,  {title: 'fodddo test'});
  await deleteData(7);

  const result = await getData();

  return (
    <html lang="en">
      <body className={inter.className}>
        {result.map(({title}:data) => (
          <div key={'id'}>
            {title}
          </div>
        ))}
        {children}
      </body>
    </html>
  )
}
