export const bankList = [
  { value: 'KDB', label: 'KDB 산업은행', code: '02' },
  { value: 'IBK', label: 'IBK 기업은행', code: '03' },
  { value: 'KB', label: '국민은행', code: '04' },
  { value: 'SUHYUP', label: '수협은행', code: '07' },
  { value: 'NH', label: '지역(단위) 농협', code: '12' },
  { value: 'NHLOCAL', label: '농협중앙회', code: '11' },
  { value: 'WOORI', label: '우리은행', code: '20' },
  { value: 'SC', label: 'SC제일은행', code: '23' },
  { value: 'CITY', label: '한국씨티은행', code: '27' },
  { value: 'DAEGU', label: '대구은행', code: '31' },
  { value: 'PUSAN', label: '부산은행', code: '32' },
  { value: 'GWANGJU', label: '광주은행', code: '34' },
  { value: 'JEJU', label: '제주은행', code: '35' },
  { value: 'JEONBUK', label: '전북은행', code: '37' },
  { value: 'GYEONGNAM', label: 'BNK 경남은행', code: '39' },
  { value: 'KFCC', label: '새마을금고', code: '45' },
  { value: 'NFCF', label: '산립조합중앙회', code: '64' },
  { value: 'EPOST', label: '우체국', code: '71' },
  { value: 'KEBHANA', label: 'KEB 하나은행', code: '81' },
  { value: 'SHINHAN', label: '신한은행', code: '88' },
  { value: 'KBANK', label: '케이뱅크', code: '89' },
  { value: 'KAKAO', label: '카카오뱅크', code: '90' },
  { value: 'TOSS', label: '토스뱅크', code: '92' },
  { value: 'YUANTA', label: '유안타증권(구,동양증권)', code: '209' },
  { value: 'KBSEC', label: 'KB증권(현대)', code: '218' },
  { value: 'MIRAEDAEWOO', label: '미래에셋대우', code: '238' },
  { value: 'SAMSUNG', label: '삼성증권', code: '240' },
  { value: 'HANKOOK', label: '한국투자증권', code: '243' },
  { value: 'NH_INVEST', label: 'NH투자증권(구,우리투자증권)', code: '247' },
  { value: 'HI_INVEST', label: '하이투자증권', code: '262' },
  { value: 'HMC_INVEST', label: '현대차증권', code: '263' },
  { value: 'SK', label: 'SK증권', code: '266' },
  { value: 'DAISHIN', label: '대신증권', code: '267' },
  { value: 'HANHWA', label: '한화증권', code: '269' },
  { value: 'SHINHAN_INVEST', label: '신한금융투자', code: '278' },
  { value: 'DONGBU', label: 'DB금융투자(구,동부증권)', code: '279' },
  { value: 'EUGENE_INVEST', label: '유진투자증권', code: '280' },
  { value: 'MERITZ_COMPREHENSIVE', label: '메리츠', code: '287' },
  { value: 'SHINYOUNG', label: '신영증권', code: '291' },
  { value: 'CAPE', label: 'CAPE Investment & Securities' },
  // { value: 'BOOKOOK', label: 'Bookook Securities' },
  // { value: 'HANA_INVEST', label: 'Hana Financial Investment' },
  // { value: 'SOLOMON_INVEST', label: 'SOLOMON INVESTMENT & SECURITIES' },
  // { value: 'EBEST', label: 'EBEST INVESTMENT & SECURITIES' },
  // { value: 'KIWOOM', label: 'Kiwoom Securities' },
  // { value: 'KYOBO', label: 'Kyobo Securities' },
  // { value: 'MIRAE', label: '미래에셋증권', },
  // { value: 'CU', label: 'National Credit Union Federation' },
  // { value: 'SANGHO', label: 'Mutual Savings Bank / Thrift Institution' },
  // { value: 'HSBC', label: 'Hongkong and Shanghai Banking Corporation' },
  // { value: 'DEUTSCHE', label: 'Deutsche Bank AG' },
  // { value: 'ANONYMOUS', label: 'Unverified Bank' },
  // { value: 'KEXIM', label: '한국 수출입 은행' },
  // { value: 'KEB', label: 'KEB 외환은행' },
] as const;
