export const deliveryList = [
  { value: 'CVS', label: 'CVS 편의점 택배' },
  { value: 'CJ', label: 'CJ 로지스틱스' },
  { value: 'POST', label: '우체국 택배' },
  { value: 'HANJIN', label: '한진 택배' },
  { value: 'GTX', label: 'GTX 로지스' },
  { value: 'LOTTE', label: '롯데글로벌로지스틱스' },
  { value: 'KGB', label: 'KGB 로지스' },
  { value: 'LOGEN', label: '로젠택배' },
  { value: 'GSI', label: 'GSI 익스프레스' },
  { value: 'KGL', label: 'KG 로지스' },
  { value: 'INTRAS', label: '인트라스' },
  { value: 'UPS', label: 'UPS' },
  { value: 'CHUNIL', label: '천일 택배' },
  { value: 'KDEXP', label: '경동 택배' },
  { value: 'HDEXP', label: '합동 택배' },
  { value: 'ILYANG', label: '일양로지스' },
  { value: 'POST_EMS', label: '우체국 EMS' },
  { value: 'DAESIN', label: '대신 택배' },
  { value: 'DHL', label: 'DHL' },
  { value: 'FEDEX', label: 'FedEx' },
  { value: 'GSM', label: 'GSM 국제 택배' },
  { value: 'WARPEX', label: 'WarpEx' },
  { value: 'WIZWA', label: '위즈택배' },
  { value: 'ACI', label: 'ACI 익스프레스' },
  { value: 'PANTOS', label: 'LX 판토스' },
  { value: 'CJ_INTERNATIONAL', label: 'CJ 로지스틱스 (국제 운송)' },
  { value: 'TNT', label: 'TNT' },
  { value: 'CU', label: 'CU 편의점 택배' },
  { value: 'KUNYOUNG', label: '건영 택배' },
  {
    value: 'LOTTE_INTERNATIONAL',
    label: '롯데글로벌로지스틱스 (국제 운송)',
  },
  { value: 'HONAM', label: '호남 택배' },
  { value: 'HANIPS', label: '한입사랑 택배' },
  { value: 'IPARCEL', label: 'i-파셀' },
  { value: 'SLX', label: 'SLX 익스프레스' },
  { value: 'USPS', label: 'USPS' },
  { value: 'WONDERS', label: '원더스 퀵' },
  { value: 'REGISTPOST', label: '등기 우편' },
  { value: 'DHLDE', label: 'DHL (독일)' },
  { value: 'EZUSA', label: '이지익스프레스' },
  { value: 'SWGEXP', label: '성원글로벌' },
  { value: 'DAEWOON', label: '대운 글로벌' },
  { value: 'DODOFLEX', label: '만나플렉스' },
  { value: 'NH_LOGIS', label: '농협 로지스' },
  { value: 'UFO', label: '우진화물(UFO로지스)' },
  { value: 'TODAY_PICKUP', label: '오늘의 픽업' },
  { value: 'QEXPRESS', label: '큐익스프레스' },
  { value: 'PINGPONG', label: '핑퐁' },
  { value: 'ETC', label: 'ETC' },
];
