import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/lib/styled-components'
import Header from '@/components/Header'
import AuthContext from '@/context/AuthContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <AuthContext>
            <Header />
            <main>{children}</main>
          </AuthContext>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
