import type { Metadata } from "next";
import { pretendard } from '@/libs/fonts';
import Header from "@/components/Header/Header";
import CustomThemeProvider from "@/provider/CustomThemeProvider";
import AuthProvider from "@/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Instantgram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <AuthProvider>
          <CustomThemeProvider>
            <Header />
            {children}
          </CustomThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
