#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
PROTECTED_BRANCHES="^(master|dev|prod)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

exit 0