function crawlingBuyDirect(mdlCode){buyDirect(mdlCode,"_self")}
function buyDirect(mdlCode,target){var stContextPath=$("#viewStContextPath").val();if(mdlCode===null||mdlCode===undefined||$.trim(mdlCode).length==0){var alertData={title:"",content:"모델코드가 없습니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}var goodsId;var option={url:stContextPath+"/xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:mdlCode},success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData=
{title:"",content:"상품을 준비중입니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else if(result.goodsIdList!=null)goodsId=result.goodsIdList[0]},error:function(response,status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option);if(goodsId!==null&&goodsId!==undefined){var reqData={goodsIds:goodsId,
stGbCd:"${view.stGbCd}",stId:"${view.stId}",mbrNo:"${session.mbrNo}",nowBuyYn:"Y",buyQtys:1,orderType:"ONCE"};var nowBuyOptions={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:reqData,success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{var form=document.createElement("form");form.setAttribute("action",stContextPath+
"order/");form.setAttribute("target",target);form.setAttribute("method","post");document.body.appendChild(form);form.submit()}},error:function(response,status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(nowBuyOptions)}}
function fnBuyDirect(mdlList){var stContextPath=$("#viewStContextPath").val();console.log("mdlList 222222=====> "+JSON.stringify(mdlList));var searchMdlParams="";var searchCompNoParams="";var qtyList=new Array;var tradeInList=new Array;if(0<mdlList.length){var mdlCodeI="";var qtyI=0;var compNoI="";var content="";var goodsOrdTpCd="";var galaxyClubTpCd="";var bespokeYnI="";var bspkPannelCodeI="";var bspkPannelCodeListI="";for(var i=0;i<mdlList.length;i++){mdlCodeI=mdlList[i].mdlCode;qtyI=mdlList[i].qty;
if(mdlList[i].compNo===null||mdlList[i].compNo===undefined||$.trim(mdlList[i].compNo).length==0)compNoI=0;else compNoI=mdlList[i].compNo;if(mdlList[i].bespokeYn===null||mdlList[i].bespokeYn===undefined)bespokeYnI="N";else bespokeYnI=mdlList[i].bespokeYn;if(mdlCodeI===null||mdlCodeI===undefined||$.trim(mdlCodeI).length==0)if(bespokeYnI=="Y")content="모델이 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";else content="모델코드를 확인하여 주시기 바랍니다.";if(qtyI===null||qtyI===undefined||qtyI<1)content="수량을 확인하여 주시기 바랍니다.";if(bespokeYnI==
"Y"){bspkPannelCodeI=mdlList[i].pannelCode;bspkPannelCodeListI=mdlList[i].pannelCode.split("|");var mdlOptions={url:stContextPath+"/xhr/bespoke/bespokeModelType",dataType:"json",type:"POST",async:false,data:{mdlCode:mdlCodeI},success:function(result){var oneDoorTypeSeq=["4","5","6","8"];var twoDoorTypeSeq=["3"];var threeDoorTypeSeq=["7","9","21"];var pannelReqLength=0;if(oneDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=1;else if(twoDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=2;
else if(threeDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=3;else pannelReqLength=4;if(bspkPannelCodeListI==""||bspkPannelCodeListI==undefined||bspkPannelCodeListI==null)content="컬러가 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";else if(bspkPannelCodeListI.length<pannelReqLength)content="모든 컬러가 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";if(content!==""){var alertData={title:"",content:content,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{var bspkCodes=mdlCodeI+
"|"+bspkPannelCodeI;buyfixedMatchAjax(bspkCodes,qtyI,"buy","")}return false},error:function(){var alertData={title:"",content:"데이터 확인이 필요합니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}};$.ajax(mdlOptions);return false}else{mdlList[i].pannelCode="";bspkPannelCodeI=mdlList[i].pannelCode;bspkPannelCodeListI=mdlList[i].pannelCode.split("|");if(mdlList[i].tradeIn=="Y")goodsOrdTpCd="TRD";else if(mdlList[i].ceTradeIn=="Y")goodsOrdTpCd="CETRD";else goodsOrdTpCd=
"";if(mdlList[i].galaxyClub=="Y"){goodsOrdTpCd+="GC";if(mdlList[i].galaxyClubTpCd===null||mdlList[i].galaxyClubTpCd===undefined||$.trim(mdlList[i].galaxyClubTpCd).length==0)content="갤럭시 클럽 캠페인 코드를 확인하여 주시기 바랍니다.";else galaxyClubTpCd=mdlList[i].galaxyClubTpCd}console.log("goodsOrdTpCd=====> "+goodsOrdTpCd);if(content!==""){var alertData={title:"",content:content,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{if(i!==mdlList.length-1){searchMdlParams+=mdlCodeI+
"^";searchCompNoParams+=compNoI+"^"}else{searchMdlParams+=mdlCodeI;searchCompNoParams+=compNoI}qtyList.push(qtyI);tradeInList.push(goodsOrdTpCd)}}}}else{var alertData={title:"",content:"데이터 확인이 필요합니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}var goodsIdList=[];var option={url:stContextPath+"/xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:searchMdlParams,compNos:searchCompNoParams},success:function(result){if(result.exCode!==
null&&result.exCode!==undefined){var alertData={title:"goodsIdsAjax",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else if(result.goodsIdList!==null)goodsIdList=result.goodsIdList},error:function(response,status,error){var alertData={title:"goodsIdsAjax.err",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};
$.ajax(option);if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:String(goodsIdList),nowBuyYn:"Y",buyQtys:String(qtyList),orderType:"ONCE",goodsOrdTpCd:String(tradeInList),galaxyClubTpCd:galaxyClubTpCd};var orderUrl=stContextPath+"order/";var nowBuyOptions={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:reqData,success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData={title:"insertCart",content:result.exMsg,
callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else if(tradeInList.includes("CETRD")||tradeInList.includes("TRD")){if(fnChkLogin("구매하기",orderUrl))location.href=orderUrl}else if(tradeInList.includes("GC")||tradeInList.includes("TRDGC"))fnChkGalaxyClub(reqData);else{var form=document.createElement("form");form.setAttribute("action",orderUrl);form.setAttribute("target","_self");form.setAttribute("method","post");document.body.appendChild(form);form.submit()}},
error:function(response,status,error){var alertData={title:"insertCart.err",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(nowBuyOptions)}}
var buyAjax=function(data){var stContextPath=$("#viewStContextPath").val();var ids="";var option1={url:stContextPath+"/xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:data},success:function(result){if(typeof result.exCode!=="undefined"){var alertData={title:"",content:"상품을 준비중입니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else ids=JSON.stringify(result.goodsIdList)},error:function(response,status,error){alert("오류");
return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option1);if(ids!=""){var option={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:{nowBuyYn:"Y",bspkGrpKeys:data,goodsIds:ids},success:function(result){if(typeof result.exCode!=="undefined"){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{var form=document.createElement("form");form.setAttribute("action",
stContextPath+"order/");form.setAttribute("target","_self");form.setAttribute("method","post");document.body.appendChild(form);form.submit()}},error:function(response,status,error){alert("오류")},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option)}};
function fnCartDirect(mdlList,cartCallMethod){var stContextPath=$("#viewStContextPath").val();console.log("mdlList=====> "+JSON.stringify(mdlList));var searchMdlParams="";var searchCompNoParams="";var qtyList=new Array;if(0<mdlList.length){var mdlCodeI="";var qtyI=0;var compNoI="";var content="";var bespokeYnI="";var bspkPannelCodeI="";var bspkPannelCodeListI="";for(var i=0;i<mdlList.length;i++){mdlCodeI=mdlList[i].mdlCode;qtyI=mdlList[i].qty;if(mdlList[i].compNo===null||mdlList[i].compNo===undefined||
$.trim(mdlList[i].compNo).length==0)compNoI=0;else compNoI=mdlList[i].compNo;if(mdlList[i].bespokeYn===null||mdlList[i].bespokeYn===undefined)bespokeYnI="N";else bespokeYnI=mdlList[i].bespokeYn;if(mdlCodeI===null||mdlCodeI===undefined||$.trim(mdlCodeI).length==0)if(bespokeYnI=="Y")content="모델이 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";else content="모델코드를 확인하여 주시기 바랍니다.";if(qtyI===null||qtyI===undefined||qtyI<1)content="수량을 확인하여 주시기 바랍니다.";if(bespokeYnI=="Y"){bspkPannelCodeI=mdlList[i].pannelCode;bspkPannelCodeListI=
mdlList[i].pannelCode.split("|");var mdlOptions={url:stContextPath+"/xhr/bespoke/bespokeModelType",dataType:"json",type:"POST",async:false,data:{mdlCode:mdlCodeI},success:function(result){var oneDoorTypeSeq=["4","5","6","8"];var twoDoorTypeSeq=["3"];var threeDoorTypeSeq=["7","9","21"];var pannelReqLength=0;if(oneDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=1;else if(twoDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=2;else if(threeDoorTypeSeq.indexOf(result.typeSeq)>-1)pannelReqLength=
3;else pannelReqLength=4;if(bspkPannelCodeListI==""||bspkPannelCodeListI==undefined||bspkPannelCodeListI==null)content="컬러가 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";else if(bspkPannelCodeListI.length<pannelReqLength)content="모든 컬러가 선택되지 않았습니다.<br/>선택 완료 후 구매해 주시기 바랍니다.";if(content!==""){var alertData={title:"",content:content,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{var bspkCodes=mdlCodeI+"|"+bspkPannelCodeI;buyfixedMatchAjax(bspkCodes,qtyI,"cart",
cartCallMethod)}return false},error:function(){var alertData={title:"",content:"데이터 확인이 필요합니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}};$.ajax(mdlOptions);return false}else{mdlList[i].pannelCode="";bspkPannelCodeI=mdlList[i].pannelCode;bspkPannelCodeListI=mdlList[i].pannelCode.split("|");if(content!==""){var alertData={title:"",content:content,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{if(i!==mdlList.length-
1){searchMdlParams+=mdlCodeI+"^";searchCompNoParams+=compNoI+"^"}else{searchMdlParams+=mdlCodeI;searchCompNoParams+=compNoI}qtyList.push(qtyI)}}}}else{var alertData={title:"",content:"데이터 확인이 필요합니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}getGoodsIds(searchMdlParams,searchCompNoParams,qtyList,cartCallMethod)}
function getGoodsIds(searchMdlParams,searchCompNoParams,qtyList,cartCallMethod){var goodsIdList=[];var stContextPath=$("#viewStContextPath").val();var option={url:stContextPath+"xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:searchMdlParams,compNos:searchCompNoParams},success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");
return false}else if(result.goodsIdList!==null){goodsIdList=result.goodsIdList;var goodsList=[];for(var i=0;i<goodsIdList.length;i++){var goods={};goods.goodsId=goodsIdList[i].trim();goods.qty=qtyList[i];goodsList.push(goods)}fnCartDirectByMultiId1(goodsList,"confirm")}},error:function(response,status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};
$.ajax(option)}
function goodsCntCart(goodsIdList,qtyList,cartCallMethod){if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:String(goodsIdList),stGbCd:"${view.stGbCd}",stId:"${view.stId}",mbrNo:"${session.mbrNo}",nowBuyYn:"N",buyQtys:String(qtyList),orderType:"ONCE"};var stContextPath=$("#viewStContextPath").val();if(cartCallMethod=="confirm"){var options={url:stContextPath+"xhr/order/goodscnt",data:reqData,done:function(data){var cartCnt=data.goodsCnt;if(cartCnt>0){var confirmData=
{content:"이미 동일한 상품이 장바구니에 있습니다.</br>추가하시겠습니까?",okBtnText:"확인",cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){if($("#commonConfirmOkBtn").text()=="확인")insertCartItemFn(reqData,cartCallMethod)});$("#commonConfirmCancelBtn").on("click",function(){return false})}else insertCartItemFn(reqData,cartCallMethod)}};ajax.call(options)}else insertCartItemFn(reqData,cartCallMethod)}}
function insertCartItemFn(reqData,cartCallMethod){var stContextPath=$("#viewStContextPath").val();var nowBuyOptions={url:stContextPath+"xhr/order/insertCart",dataType:"json",type:"POST",data:reqData,async:false,success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{if(cartCallMethod=="confirm"){var confirmData={content:"제품이 장바구니에 추가되었습니다.<br>(현재 총 "+
result.cartCnt+"개의 제품이 장바구니에 담겼습니다.)",okBtnText:"쇼핑 계속하기",cancelBtnText:"장바구니 이동"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){return false});$("#commonConfirmCancelBtn").on("click",function(){if($("#commonConfirmCancelBtn").text()=="장바구니 이동")location.href=stContextPath+"cart/"});if(result.cartCnt!==0){$(".cart-inner-count").css("display","block");$(".cart-inner-count").html(result.cartCnt)}else $(".cart-inner-count").css("display",
"none")}else location.href=stContextPath+"cart/";return false}},error:function(response,status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(nowBuyOptions);return false}
var buyfixedMatchAjax=function(dataParam,qtyList,type,cartCallMethod){var stContextPath=$("#viewStContextPath").val();var self_=this;var fixedmodel="";var yesCallback=function(){buyAjax(fixedmodel+":::1")};dataParam=dataParam.replace(/\|/g,"^");var noCallback=function(){buyAjax(dataParam)};var coCallback=function(){};var params={"storeCd":"sec","productCode":+dataParam};var option={url:stContextPath+"/xhr/bespoke/fixedMatchAjax",dataType:"json",type:"POST",data:params,jsonpCallback:"jsonpcallback_bespoke",
success:function(rtnjson){var price1="0";var price2="0";if(rtnjson.fixedMatchResult.code=="Y"){fixedmodel=rtnjson.fixedMatchResult.data.fixedMdl;price1=controlNumber.numberWithCommas(selectPrice);price2=controlNumber.numberWithCommas(rtnjson.fixedMatchResult.data.bPrice);popup.confirm8(1,"가격비교 안내 및 fixed 제품 구매",price1,price2,yesCallback,noCallback,coCallback);return false}else if(type=="cart")cartAjax(dataParam,qtyList,cartCallMethod);else buyAjax(dataParam)},error:function(response,status,error){alert("fixedMatchAjax.오류")},
beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option)};
var cartAjax=function(data,qtyList,cartCallMethod){var stContextPath=$("#viewStContextPath").val();var cartParam="";var ids="";var option1={url:stContextPath+"/xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:data},success:function(result){if(typeof result.exCode!=="undefined"){var alertData={title:"",content:"상품을 준비중입니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else ids=JSON.stringify(result.goodsIdList)},error:function(response,
status,error){alert("오류");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option1);goodsIdsTmp=ids.replace(/"/g,"");goodsIdsTmp=goodsIdsTmp.replace("[","");goodsIdsTmp=goodsIdsTmp.replace("]","");var bspkGoodsIdsList=goodsIdsTmp.split(",");if(cartCallMethod=="confirm"){var options={url:stContextPath+"/xhr/order/goodscnt",data:{goodsIds:bspkGoodsIdsList,nowBuyYn:"N",buyQtys:String(qtyList),orderType:"ONCE",bspkGrpKeys:data,bspkGoodsYn:"Y"},done:function(resData){var cartCnt=
resData.goodsCnt;if(cartCnt>0){var confirmData={content:"이미 동일한 상품이 장바구니에 있습니다.</br>추가하시겠습니까?",okBtnText:"확인",cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){if($("#commonConfirmOkBtn").text()=="확인")insertBespokeCartFn(data,ids,cartCallMethod)});$("#commonConfirmCancelBtn").on("click",function(){return false})}else insertBespokeCartFn(data,ids,cartCallMethod)}};ajax.call(options)}else insertBespokeCartFn(data,
ids,cartCallMethod)};
var insertBespokeCartFn=function(data,ids,cartCallMethod){var stContextPath=$("#viewStContextPath").val();if(ids!=""){var option={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:{nowBuyYn:"N",bspkGrpKeys:data,goodsIds:ids},success:function(result){if(typeof result.exCode!=="undefined"){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{if(cartCallMethod=="confirm"){var confirmData={content:"제품이 장바구니에 추가되었습니다.<br>장바구니로 이동하시겠습니까?",
okBtnText:"이동",cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){if($("#commonConfirmOkBtn").text()=="이동")location.href=stContextPath+"cart/"});$("#commonConfirmCancelBtn").on("click",function(){return false})}else location.href=stContextPath+"cart/";return false}},error:function(response,status,error){alert("오류")},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};
$.ajax(option)}};
function presentDirect(mdlCode,target){if(mdlCode===null||mdlCode===undefined||$.trim(mdlCode).length==0){var alertData={title:"",content:"모델코드가 없습니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}var stContextPath=$("#viewStContextPath").val();var goodsId;var option={url:stContextPath+"/xhr/bespoke/goodsIdsAjax",dataType:"json",type:"POST",async:false,data:{bspkGrpKeys:mdlCode},success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData=
{title:"",content:"상품을 준비중입니다.",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else if(result.goodsIdList!=null)goodsId=result.goodsIdList[0]},error:function(response,status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(option);if(goodsId!==null&&goodsId!==undefined){var reqData={goodsIds:goodsId,
stGbCd:"${view.stGbCd}",stId:"${view.stId}",mbrNo:"${session.mbrNo}",nowBuyYn:"Y",buyQtys:1,orderType:"ONCE"};var nowBuyOptions={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:reqData,success:function(result){if(result.exCode!==null&&result.exCode!==undefined){var alertData={title:"",content:result.exMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}else{var msg="선물하기";if(fnChkLogin(msg,location.pathname)){var cartId=document.createElement("input");
cartId.setAttribute("name","cartId");cartId.setAttribute("value",result.cartId);var presentYn=document.createElement("input");presentYn.setAttribute("name","presentYn");presentYn.setAttribute("value","Y");var form=document.createElement("form");form.setAttribute("action",stContextPath+"present/presentSend/");form.setAttribute("target",target);form.setAttribute("method","post");form.appendChild(cartId);form.appendChild(presentYn);document.body.appendChild(form);form.submit()}}},error:function(response,
status,error){var alertData={title:"",content:"오류",callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(nowBuyOptions)}}function crawlingBuyDirectById(goodsId){fnBuyDirectBySingleId(goodsId,"_self")}
function fnCartDirectByMultiId1(goodsList,cartCallMethod){console.log("goodsList=====> "+JSON.stringify(goodsList));var searchGoodsParams="";var searchCompNoParams="";var qtyList=new Array;if(0<goodsList.length){var goodsId="";var qtyI=0;var compNoI="";var content="";for(var i=0;i<goodsList.length;i++){goodsId=goodsList[i].goodsId;qtyI=goodsList[i].qty;if(goodsId===null||goodsId===undefined||$.trim(goodsId).length==0)content="상품아이디를 확인하여 주시기 바랍니다.";if(goodsList[i].compNo===null||goodsList[i].compNo===
undefined||$.trim(goodsList[i].compNo).length==0)compNoI=0;else compNoI=goodsList[i].compNo;if(qtyI===null||qtyI===undefined||qtyI<1)content="수량을 확인하여 주시기 바랍니다.";if(content!==""){fnAlertMessage(content);return false}else{if(i!==goodsList.length-1){searchGoodsParams+=goodsId+"^";searchCompNoParams+=compNoI+"^"}else{searchGoodsParams+=goodsId;searchCompNoParams+=compNoI}qtyList.push(qtyI)}}}else{fnAlertMessage("데이터 확인이 필요합니다.");return false}var goodsIdList=fnCheckGoodsStatus(searchGoodsParams);if(goodsIdList!==
null&&goodsIdList!==undefined&&goodsIdList.length>0)goodsCntCart(goodsIdList,qtyList,cartCallMethod)}
function cartDirectMdlCode(mdlCode,qty){var mdlList=[];var vel=true;if(Array.isArray(mdlCode))for(var i=0;i<mdlCode.length;i++){var mdl={};mdl.mdlCode=mdlCode[i].trim();mdl.qty=ifNullQty(qty,i);mdlList.push(mdl)}else if(typeof mdlCode=="string")if(mdlCode.includes(",")){var spiltList=mdlCode.split(",");for(var i=0;i<spiltList.length;i++){var mdl={};mdl.mdlCode=spiltList[i].trim();mdl.qty=ifNullQty(qty,i);mdlList.push(mdl)}}else{var mdl={};mdl.mdlCode=mdlCode;mdl.qty=ifNullQty(qty);mdlList.push(mdl)}else{vel=
false;fnAlertMessage("잘못된 모델코드 형식입니다.")}if(vel)fnCartDirect(mdlList,"confirm")}
function cartDirectGoodsId(goodsId,qty){var goodsList=[];var vel=true;if(Array.isArray(goodsId))for(var i=0;i<goodsId.length;i++){var goods={};goods.goodsId=goodsId[i].trim();goods.qty=ifNullQty(qty,i);goodsList.push(goods)}else if(typeof goodsId=="string")if(goodsId.includes(",")){var spiltList=goodsId.split(",");for(var i=0;i<spiltList.length;i++){var goods={};goods.goodsId=spiltList[i].trim();goods.qty=ifNullQty(qty,i);goodsList.push(goods)}}else{var goods={};goods.goodsId=goodsId;goods.qty=ifNullQty(qty);
goodsList.push(goods)}else{vel=false;fnAlertMessage("잘못된 상품아이디 형식")}if(vel)fnCartDirectByMultiId1(goodsList,"confirm")}function ifNullQty(qty,index){if(qty!=null&&qty.length!=0)if(Array.isArray(qty)&&index!=null)return qty[index].trim();else if(typeof qty=="string")if(qty.includes(",")&&index!=null){var qtyList=qty.split(",");return qtyList[index].trim()}else return qty;else return 1;else return 1}
function fnChkLogin(msg,returnUrl){var stContextPath=$("#viewStContextPath").val();var ret=false;var options={url:stContextPath+"/xhr/goods/loginCheck",type:"POST",async:false,done:function(data){if(!data.isLogin){ret=false;var confirmData={content:"로그인 후 "+msg+"가 가능합니다.<br/>로그인 하시겠습니까?",okBtnText:"확인",cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").hide();$("#commonConfirmOkBtn").on("click",function(){location.href=stContextPath+"member/indexLogin/?returnUrl="+
returnUrl;return false});$("#commonConfirmCancelBtn").on("click",function(){return false})}else ret=true}};ajax.call(options);return ret}
function fnChkGalaxyClub(reqData){var stContextPath=$("#viewStContextPath").val();var ret=false;var options={url:stContextPath+"xhr/goods/galaxyClubCheck",type:"POST",data:reqData,async:false,done:function(data){if(!data.isLogin){var confirmData={content:"로그인 이후 구매하기가 가능 합니다<br/>로그인 하시겠습니까?",okBtnText:"확인",cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").hide();$("#commonConfirmOkBtn").on("click",function(){location.href=stContextPath+"member/indexLogin/?returnUrl="+
location.pathname;return false});$("#commonConfirmCancelBtn").on("click",function(){return false})}else{var alertMsg="";if(data.membershipNo!=null){if(data.isGalaxyCmpnYn!=null){if(data.isGalaxyCmpnYn=="N"&&data.prgrStatCd==null)location.href=stContextPath+"order/";else if(data.isGalaxyCmpnYn=="N"&&data.prgrStatCd!=null)if(data.prgrStatCd=="01")alertMsg="<span class='blue-color'>"+data.clubNm+"</span>에<br class='pc-ver'> 가입신청이 진행 중이므로<br class='pc-ver'> My 갤럭시 클럽 대상 제품을<br class='pc-ver'> 추가 구매할 수 없습니다.";
else if(data.prgrStatCd=="02")alertMsg="<span class='blue-color'>"+data.clubNm+"</span>에<br class='pc-ver'> 가입신청이 완료되었으므로<br class='pc-ver'> My 갤럭시 클럽 대상 제품을<br class='pc-ver'> 추가 구매할 수 없습니다.";else{if(data.prgrStatCd=="03")alertMsg="<span class='blue-color'>"+data.clubNm+"</span>에<br class='pc-ver'> 가입이 완료되었으므로<br class='pc-ver'> My 갤럭시 클럽 대상 제품을<br class='pc-ver'> 추가 구매할 수 없습니다."}else alertMsg="이미 <span class='blue-color'>"+data.clubNm+"</span>에<br class='pc-ver'> 포함되어 있는 제품을 구매하셨습니다.<br>"+"동일 "+
data.clubNm+"에<br class='pc-ver'> 포함되어 있는 제품은<br class='pc-ver'> 회원 1인당 1대만 구매 가능합니다.";if(alertMsg!=""){var confirmData$0={content:alertMsg,cancelBtnText:"닫기"};commonConfirm(confirmData$0);openLayer("commonConfirm");$("#commonConfirmOkBtn").hide();$("#commonConfirmCancelBtn").on("click",function(){return false});return ret}}}else{var confirmData$1={content:"My 갤럭시 클럽 제품을 구매하시려면<br class='pc-ver'> 멤버십 회원으로 먼저 가입하셔야 합니다.<br>멤버십 회원으로 가입 하시겠습니까?",okBtnText:"확인",cancelBtnText:"취소"};commonConfirm(confirmData$1);
openLayer("commonConfirm");$("#commonConfirmOkBtn").on("click",function(){location.href=stContextPath+"membership/point/";return false});$("#commonConfirmCancelBtn").on("click",function(){return false});return ret}ret=true}}};ajax.call(options);return ret}
function fnCheckGoodsStatus(goodsIdParam){var stContextPath=$("#viewStContextPath").val();var goodsIdList=[];var checkOption={url:stContextPath+"xhr/goods/checkGoodsStatus",dataType:"json",type:"POST",async:false,data:{grpKeys:goodsIdParam},success:function(result){if(result.exCode!==null&&result.exCode!==undefined){fnAlertMessage("상품을 준비중입니다.");return false}else if(result!=null)goodsIdList=result},error:function(response,status,error){fnAlertMessage("[오류] goodsIdsAjax");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",
true)},complete:function(){}};$.ajax(checkOption);return goodsIdList}function fnAlertMessage(alertMsg){var alertData={title:"",content:alertMsg,callBack:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert")}
function fnInsertCart(reqData){var stContextPath=$("#viewStContextPath").val();var cartResult=null;var nowBuyOptions={url:stContextPath+"/xhr/order/insertCart",dataType:"json",type:"POST",data:reqData,async:false,success:function(result){if(result.exCode!==null&&result.exCode!==undefined){fnAlertMessage(result.exMsg);return false}else{cartResult=result;if("N"===reqData.nowBuyYn)if("confirm"===reqData.cartCallMethod){var confirmData={content:"제품이 장바구니에 추가되었습니다.<br>(현재 총 "+result.cartCnt+"개의 제품이 장바구니에 담겼습니다.)",
okBtnText:"쇼핑 계속하기",cancelBtnText:"장바구니 이동"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){return false});$("#commonConfirmCancelBtn").on("click",function(){if($("#commonConfirmCancelBtn").text()=="장바구니 이동"){location.href=stContextPath+"cart/";return false}});if(result.cartCnt!==0){$(".cart-inner-count").css("display","block");$(".cart-inner-count").html(result.cartCnt)}else $(".cart-inner-count").css("display",
"none")}else{location.href=stContextPath+"cart/";return false}}},error:function(response,status,error){fnAlertMessage("[오류] insertCart");return false},beforeSend:function(xhr){xhr.setRequestHeader("ajax",true)},complete:function(){}};$.ajax(nowBuyOptions);return cartResult}
function fnCartDirectByMultiId(goodsList,cartCallMethod){var stContextPath=$("#viewStContextPath").val();console.log("goodsList=====> "+JSON.stringify(goodsList));var searchGoodsParams="";var searchCompNoParams="";var qtyList=new Array;var tradeInList=new Array;if(0<goodsList.length){var goodsId="";var qtyI=0;var compNoI="";var content="";var goodsOrdTpCd="";var galaxyClubTpCd="";for(var i=0;i<goodsList.length;i++){goodsId=goodsList[i].goodsId;qtyI=goodsList[i].qty;if(goodsId===null||goodsId===undefined||
$.trim(goodsId).length==0)content="상품아이디를 확인하여 주시기 바랍니다.";if(goodsList[i].compNo===null||goodsList[i].compNo===undefined||$.trim(goodsList[i].compNo).length==0)compNoI=0;else compNoI=goodsList[i].compNo;if(qtyI===null||qtyI===undefined||qtyI<1)content="수량을 확인하여 주시기 바랍니다.";if(goodsList[i].tradeIn=="Y")goodsOrdTpCd="TRD";else if(goodsList[i].ceTradeIn=="Y")goodsOrdTpCd="CETRD";else goodsOrdTpCd="";if(goodsList[i].galaxyClub=="Y")content="My 갤럭시 클럽 상품은 장바구니에 담을 수 없습니다.";console.log("goodsOrdTpCd=====> "+
goodsOrdTpCd);if(content!==""){fnAlertMessage(content);return false}else{if(i!==goodsList.length-1){searchGoodsParams+=goodsId+"^";searchCompNoParams+=compNoI+"^"}else{searchGoodsParams+=goodsId;searchCompNoParams+=compNoI}qtyList.push(qtyI);tradeInList.push(goodsOrdTpCd)}}if(tradeInList.includes("CETRD")||tradeInList.includes("TRD"))if(!fnChkLogin("중고 추가 보상 상품 장바구니 담기",location.pathname))return false}else{fnAlertMessage("데이터 확인이 필요합니다.");return false}var goodsIdList=fnCheckGoodsStatus(searchGoodsParams);
if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:String(goodsIdList),nowBuyYn:"N",buyQtys:String(qtyList),orderType:"ONCE",cartCallMethod:cartCallMethod,goodsOrdTpCd:String(tradeInList),galaxyClubTpCd:galaxyClubTpCd};if(cartCallMethod=="confirm"){var options={url:stContextPath+"xhr/order/goodscnt",data:reqData,async:false,done:function(data){var cartCnt=data.goodsCnt;if(cartCnt>0){var confirmData={content:"이미 동일한 상품이 장바구니에 있습니다.</br>추가하시겠습니까?",okBtnText:"확인",
cancelBtnText:"취소"};commonConfirm(confirmData);openLayer("commonConfirm");$("#closeCommonConfirmBtn").css("display","none");$("#commonConfirmOkBtn").on("click",function(){if($("#commonConfirmOkBtn").text()=="확인"){fnInsertCart(reqData);return false}});$("#commonConfirmCancelBtn").on("click",function(){return false})}else fnInsertCart(reqData)}};ajax.call(options)}else fnInsertCart(reqData)}}
function fnBuyDirectBySingleId(goodsId,target,naverPay){if(goodsId===null||goodsId===undefined||$.trim(goodsId).length==0){fnAlertMessage("상품아이디가 없습니다.");return false}var stContextPath=$("#viewStContextPath").val();var goodsIdList=fnCheckGoodsStatus(goodsId);if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:goodsIdList,nowBuyYn:"Y",buyQtys:1,orderType:"ONCE"};if(fnInsertCart(reqData)!=null){var form=document.createElement("form");form.setAttribute("action",
stContextPath+"order/");form.setAttribute("target",target);form.setAttribute("method","post");if(naverPay!==null&&naverPay!==undefined&&naverPay=="Y"){var input=document.createElement("input");input.setAttribute("type","text");input.setAttribute("name","naverPay");input.setAttribute("value","Y");form.appendChild(input)}document.body.appendChild(form);form.submit()}}}
function fnBuyDirectByMultiId(goodsList,naverPay){var stContextPath=$("#viewStContextPath").val();console.log("goodsList 222222=====> "+JSON.stringify(goodsList));var searchGoodsParams="";var searchCompNoParams="";var qtyList=new Array;var tradeInList=new Array;if(0<goodsList.length){var goodsId="";var qtyI=0;var compNoI="";var content="";var goodsOrdTpCd="";var galaxyClubTpCd="";var pckStrNo="";var pckGoodsIdList=[];for(var i=0;i<goodsList.length;i++){goodsId=goodsList[i].goodsId;qtyI=goodsList[i].qty;
pckStrNo=goodsList[i].pckStrNo;pckGoodsIdList.push(goodsId);if(goodsId===null||goodsId===undefined||$.trim(goodsId).length==0)content="상품아이디를 확인하여 주시기 바랍니다.";if(goodsList[i].compNo===null||goodsList[i].compNo===undefined||$.trim(goodsList[i].compNo).length==0)compNoI=0;else compNoI=goodsList[i].compNo;if(qtyI===null||qtyI===undefined||qtyI<1)content="수량을 확인하여 주시기 바랍니다.";if(goodsList[i].tradeIn=="Y")goodsOrdTpCd="TRD";else if(goodsList[i].ceTradeIn=="Y")goodsOrdTpCd="CETRD";else goodsOrdTpCd="";if(goodsList[i].galaxyClub==
"Y"){goodsOrdTpCd+="GC";if(goodsList[i].galaxyClubTpCd===null||goodsList[i].galaxyClubTpCd===undefined||$.trim(goodsList[i].galaxyClubTpCd).length==0)content="갤럭시 클럽 캠페인 코드를 확인하여 주시기 바랍니다.";else galaxyClubTpCd=goodsList[i].galaxyClubTpCd}console.log("goodsOrdTpCd=====> "+goodsOrdTpCd);if(content!==""){fnAlertMessage(content);return false}else{if(i!==goodsList.length-1){searchGoodsParams+=goodsId+"^";searchCompNoParams+=compNoI+"^"}else{searchGoodsParams+=goodsId;searchCompNoParams+=compNoI}qtyList.push(qtyI);
tradeInList.push(goodsOrdTpCd)}}}else{fnAlertMessage("데이터 확인이 필요합니다.");return false}var goodsIdList;if(!pckStrNo)goodsIdList=fnCheckGoodsStatus(searchGoodsParams);else goodsIdList=pckGoodsIdList;if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:String(goodsIdList),nowBuyYn:"Y",buyQtys:String(qtyList),orderType:"ONCE",goodsOrdTpCd:String(tradeInList),galaxyClubTpCd:galaxyClubTpCd,pckStrNo:pckStrNo};var orderUrl=stContextPath+"order/";if(fnInsertCart(reqData)!=
null)if(tradeInList.includes("CETRD")||tradeInList.includes("TRD")){if(fnChkLogin("구매하기",orderUrl))location.href=orderUrl}else if(tradeInList.includes("GC")||tradeInList.includes("TRDGC"))fnChkGalaxyClub(reqData);else{var form=document.createElement("form");form.setAttribute("action",orderUrl);form.setAttribute("target","_self");form.setAttribute("method","post");if(naverPay!==null&&naverPay!==undefined&&naverPay=="Y"){var input=document.createElement("input");input.setAttribute("type","text");input.setAttribute("name",
"naverPay");input.setAttribute("value","Y");form.appendChild(input)}document.body.appendChild(form);form.submit()}}}
function fnPresentDirectBySingleId(goodsId,target){if(goodsId===null||goodsId===undefined||$.trim(goodsId).length==0){fnAlertMessage("상품아이디가 없습니다.");return false}var stContextPath=$("#viewStContextPath").val();var goodsIdList=fnCheckGoodsStatus(goodsId);if(goodsIdList!==null&&goodsIdList!==undefined&&goodsIdList.length>0){var reqData={goodsIds:goodsIdList,nowBuyYn:"Y",buyQtys:1,orderType:"ONCE"};var cartResult=fnInsertCart(reqData);if(cartResult!=null){var msg="선물하기";if(fnChkLogin(msg,location.pathname)){var cartId=
document.createElement("input");cartId.setAttribute("name","cartId");cartId.setAttribute("value",cartResult.cartId);var presentYn=document.createElement("input");presentYn.setAttribute("name","presentYn");presentYn.setAttribute("value","Y");var form=document.createElement("form");form.setAttribute("action",stContextPath+"present/presentSend/");form.setAttribute("target",target);form.setAttribute("method","post");form.appendChild(cartId);form.appendChild(presentYn);document.body.appendChild(form);
form.submit()}}}}function fnOpenEnergyCalculatorPopUpLayer(){var popAddr=$(location).attr("origin")+"/sec/energyCalculator/";window.open(popAddr)}function fnOpenEnergyBefore(){var option={url:$(location).attr("origin")+"/sec/"+"energyPopUp/",dataType:"html",type:"GET",success:function(data){$("#layer").empty();$("#layer").append(data)}};$.ajax(option)}
function getEnergyOptions(param){var option={url:$(location).attr("origin")+"/sec/"+"xhr/energy/getEnergyOptions",type:"POST",data:param,done:function(data){var gbUl=$("#gbUl");var testYearUl=$("#testYearUl");var grdUl=$("#grdUl");var cateUl=$(".energy-prd-slider");if(data.energyOptions!=null)if("testYear"in param){grdUl.empty();var htmlGrUl="";for(var i=0;i<data.energyOptions.length;i++){var option=data.energyOptions[i];htmlGrUl+='<li name="energyGrd" role="option" class="droplist-item" data-omni="'+
option.dataOmni+'">'+option.energyGrd+"</li>"}grdUl.append(htmlGrUl)}else if("ctgryGbCd"in param){testYearUl.empty();grdUl.empty();var testYearUlHtml="";for(var i=0;i<data.energyOptions.length;i++){var option=data.energyOptions[i];testYearUlHtml+='<li name="testYear" role="option" class="droplist-item" data-omni="'+option.dataOmni+'">'+option.testYear+"</li>"}testYearUl.append(testYearUlHtml)}else if("energyCalCtgry"in param){gbUl.empty();testYearUl.empty();grdUl.empty();var gbUlHtml="";for(var i=
0;i<data.energyOptions.length;i++){var option=data.energyOptions[i];gbUlHtml+='<li name="gbItem" role="option" class="droplist-item" data-checked="false" data-cate="'+option.energyCalCtgry+'" data-gb="'+option.ctgryGbCd+'" data-omni="'+option.dataOmni+'">'+option.gbStr+"</li>"}gbUl.append(gbUlHtml)}}};ajax.call(option)}
function fnOpenEnergyRecommendGoodsPopUpLayer(data){var option={url:$(location).attr("origin")+"/sec/"+"xhr/energy/getEnergyRecommendGoods/",dataType:"html",type:"POST",data:data,success:function(data){$("#layer").empty();$("#layer").append(data)}};$.ajax(option)}
function fnGoodsCommentData(goodsId,stId,bestYn,limit){var stContextPath=$("#viewStContextPath").val();var returnUrl="";var goodsCommentData="";var selectParam={goodsId:goodsId,stId:stId,bestYn:bestYn=="Y"?bestYn:"",limit:limit,viewType:"img"};var options={url:stContextPath+"xhr/goods/selectTopBestGoodsComment",data:selectParam,async:false,done:function(data){if(!!data)if(data.topBestGoodsCommentList.length>0){returnUrl=stContextPath+data.topBestGoodsCommentList[0].goodsDetailUrl+"?focus=review";
data.returnUrl=returnUrl;goodsCommentData=data}else goodsCommentData=""}};ajax.call(options);return goodsCommentData}
function fnOpenPickUpStorePop(goodsInfo){var storePickUpOptions={url:$(location).attr("origin")+"/sec/"+"xhr/goods/storePickupList",data:goodsInfo,type:"POST",dataType:"html",done:function(data){$objLayer=$("#popupLayer").addClass("layer-storepickup advancement");var t=$objLayer.attr("id");$objLayer.html(data);if($(".layer-pop").is(":visible"))LAYERZINDEX++;else LAYERZINDEX=300;$objLayer.show().css("z-index",LAYERZINDEX).attr("aria-hidden",false).attr("data-zindex",LAYERZINDEX).focus();$objLayer.find(".pop-close").data("activeTarget",
t);if(!$objLayer.hasClass("nomask")){var zidx=parseInt($("#"+t).attr("data-zindex"))-1;$("body").append("<div id='mask' data-mask-target='"+t+"' style='z-index:"+zidx+"'></div>");$("#mask").fadeIn().data("activeTarget",t);scrollLock("lock")}if(!$("body").children().is("#mask"))$("body").append("<div id='mask'></div>");$("#mask").fadeIn().data("activeTarget",$objLayer.data("popup-layer"));$("#commonAlert a").attr("onblur","$('#commonAlert').focus();");$("#commonAlert").attr("onblur","$('#commonAlert a').focus();");
$objLayer.find(".pop-close").off().on("click",function(){$objLayer.removeAttr("style").removeAttr("data-zindex").attr("aria-hidden",true).hide();$objLayer.empty();$("body").css("overflow","");if($objLayer.hasClass("layer-storepickup"))$objLayer.removeClass("layer-storepickup");if($objLayer.hasClass("layer-gatherview"))$objLayer.removeClass("layer-gatherview");if($objLayer.hasClass("popup-comm-video"))$objLayer.removeClass("popup-comm-video");if($objLayer.hasClass("popup-comm-img360"))$objLayer.removeClass("popup-comm-img360");
if($objLayer.hasClass("popup-comm-gallery"))$objLayer.removeClass("popup-comm-gallery");$("#mask[data-mask-target='"+t+"']").fadeOut("fast").remove();scrollLock("unlock");LAYERZINDEX--;$(this).off()})}};ajax.call(storePickUpOptions)}
function setChoosenPickupStoreForBuyNow(data,pickupCount,buyNowYn){var plazaNmId="#plazaNm-"+data.goodsId;var plazaNoId="#plazaNo-"+data.goodsId;var storeAddrId="#storeAddr-"+data.goodsId;$(plazaNmId).text(data.plazaNm);$(plazaNoId).text(data.plazaNo);$(storeAddrId).text("("+storePickupManager.genFullAddress(data)+")");if(buyNowYn=="Y"){var goodsList=[{goodsId:data.goodsId,qty:1,compNo:data.goodsId,pckStrNo:data.plazaNo}];fnBuyDirectByMultiId(goodsList)}}
function fnRegisterRestockAlarm(goodsId,ntcSndTg,ntcSndTgHp){if(!goodsId){var alertData={title:"",content:"오류가 발생하였습니다.<br>관리자에게 문의하시기 바랍니다.<br> [No Parameter]",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return false}if(!ntcSndTg&&!ntcSndTgHp){var alertData$2={title:"",content:"정보를 입력해주시기 바랍니다.",callback:"",btnText:"확인"};commonAlert(alertData$2);openLayer("commonAlert");return false}var stContextPath=$("#viewStContextPath").val();var result=false;var param={goodsId:goodsId,
ntcSndTg:ntcSndTg,ntcSndTgHp:ntcSndTgHp};var options={url:stContextPath+"xhr/mypage/interest/registerRestockAlarm",data:param,async:false,done:function(data){if(!!data){result=data.result;var alertData$3={title:"",content:data.msg,callback:"",btnText:"확인"};commonAlert(alertData$3);openLayer("commonAlert")}else{var alertData$4={title:"",content:"오류가 발생하였습니다.<br>관리자에게 문의하시기 바랍니다.<br> [No response]",callback:"",btnText:"확인"};commonAlert(alertData$4);openLayer("commonAlert")}}};ajax.call(options);return result}
;
