function openCtaLink(url,target){if(url.indexOf("javascript:downloadFileCms")>=0){var sIdx=url.indexOf("(");var eIdx=url.indexOf(")");var lettNo=url.substring(sIdx+1,eIdx);downloadFileCms(lettNo)}else try{var lowerUrl="";if(typeof url==="string")lowerUrl=url.toLowerCase();if(stGbCd==10)if(lowerUrl.indexOf("galaxycampusday_2212")>=0||lowerUrl.indexOf("galaxycampus/?galaxycampusday")>=0)NetFunnel_Action({action_id:"b2b2c_kv_cta"},function(ev,ret){window.open(url,target)});else if(lowerUrl.indexOf("galaxycampus/?2023GCSfestival")>=
0||lowerUrl.indexOf("event/galaxy-watch6/preorder")>=0||lowerUrl.indexOf("event/galaxy-watch6/launching")>=0||lowerUrl.indexOf("event/galaxy-z-fold5/thom-browne-edition")>=0)NetFunnel_Action({action_id:"b2c_kv_cta"},function(ev,ret){window.open(url,target)});else if(lowerUrl.indexOf("event/galaxy-tabs9/preorder")>=0||lowerUrl.indexOf("event/galaxy-tabs9/launching")>=0)NetFunnel_Action({action_id:"b2c_kv_cta2"},function(ev,ret){window.open(url,target)});else if(lowerUrl.indexOf("galaxy-z-fold5/preorder")>=
0||lowerUrl.indexOf("galaxy-z-fold5/launching")>=0||lowerUrl.indexOf("galaxy-z-flip5/preorder")>=0||lowerUrl.indexOf("galaxy-z-flip5/launching")>=0)NetFunnel_Action({action_id:"b2c_kv_cta3"},function(ev,ret){window.open(url,target)});else window.open(url,target);else if(stGbCd==20)if(lowerUrl.indexOf("all-mobile-galaxy-a53")>=0)NetFunnel_Action({action_id:"fnet_kv_cta"},function(ev,ret){window.open(url,target)});else window.open(url,target);else if(stGbCd==30)if(lowerUrl.indexOf("all-mobile-galaxy-a53")>=
0)NetFunnel_Action({action_id:"fnet_kv_cta2"},function(ev,ret){window.open(url,target)});else window.open(url,target);else if(stGbCd==80)if(lowerUrl.indexOf("galaxycampusday_2212")>=0||lowerUrl.indexOf("galaxycampus/?galaxycampusday")>=0||lowerUrl.indexOf("eventlist/2023GCSfestival")>=0||lowerUrl.indexOf("eventlist/galaxy-watch6/preorder")>=0||lowerUrl.indexOf("eventlist/galaxy-watch6/launching")>=0)NetFunnel_Action({action_id:"b2b2c_kv_cta"},function(ev,ret){window.open(url,target)});else if(lowerUrl.indexOf("eventlist/galaxy-tabs9/preorder")>=
0||lowerUrl.indexOf("eventlist/galaxy-tabs9/launching")>=0)NetFunnel_Action({action_id:"b2b2c_kv_cta2"},function(ev,ret){window.open(url,target)});else if(lowerUrl.indexOf("eventlist/galaxy-z-fold5/preorder")>=0||lowerUrl.indexOf("eventlist/galaxy-z-fold5/launching")>=0||lowerUrl.indexOf("eventlist/galaxy-z-flip5/preorder")>=0||lowerUrl.indexOf("eventlist/galaxy-z-flip5/launching")>=0)NetFunnel_Action({action_id:"b2b2c_kv_cta3"},function(ev,ret){window.open(url,target)});else window.open(url,target);
else window.open(url,target)}catch(e){window.open(url,target)}}function compLayerOpenPlay(elem){if($(elem).find("video").length>0)$(elem).find("video").get(0).play()}
$(function(){$(window).resize(function(){var winw=$(window).width();if(winw>800){$(".wrap-component").find(".visual-area").find("img").each(function(){var src=$(this).attr("data-pcimg-src");$(this).attr("src",src)});$(".gallery-carousel").find(".visual-area").find("a").each(function(){var src=$(this).attr("data-pc-src-origin");$(this).attr("data-src-origin",src)})}else{$(".wrap-component").find(".visual-area").find("img").each(function(){var src=$(this).attr("data-mimg-src");if(src!="")$(this).attr("src",
src)});$(".gallery-carousel").find(".visual-area").find("a").each(function(){var src=$(this).attr("data-mo-src-origin");if(src!="")$(this).attr("data-src-origin",src)})}}).resize();$(document).on("click","[data-popup-target]",function(e){e.preventDefault();var target=$(this).attr("data-popup-target");if($("#"+target).hasClass("popup-comp-player"))if(!$("#"+target).hasClass("embed"))$("#mask").addClass("video-player")});$(document).on("click",".popup-comp-player .pop-close, #mask.video-player",function(e){e.preventDefault();
if($(this).parents(".popup-comp-player").length>0){var video=$(this).parents(".popup-comp-player").find("video");if(video.length>0)video.get(0).pause()}});var $galleyMainSliderSlide=$(".slider-grid-gallery").find(".slide-visual");$galleyMainSliderSlide.find(".visual").click(function(e){e.preventDefault();var name=$(this).attr("data-popup-name");var idx=$(this).attr("data-visual-index");$(this).attr("data-popup-target",name);displayGallery($(this),idx);setTimeout(function(){$("#mask").addClass("gallery")},
100)});var setGalleryDetail={infinite:false,arrow:true,slidesToShow:1,slidesToScroll:1,centerMode:true,fade:true,cssEase:"linear",responsive:[{breakpoint:801,settings:{arrows:true}}]};var initGalleryDetail;function displayGallery(elem,idx){var $html="";var popup=elem.attr("data-popup-name");elem.parents(".slide-visual").find(".row").each(function(){$(this).find("a").each(function(){var origin=$(this).attr("data-src-origin");var desc=$(this).find("img").attr("alt");$html+="<div class='big'><img src='"+
origin+"' alt='"+desc+"'></div>"})});$("#"+popup).find(".slider-gallery-detail").not(".slick-initialized").html($html);setTimeout(function(){initGalleryDetail=$("#"+popup).find(".slider-gallery-detail").not(".slick-initialized").slick(setGalleryDetail);initGalleryDetail.slick("slickGoTo",idx)},300)}$(document).on("click",".popup-comp-gallery .pop-close, #mask.gallery",function(e){e.preventDefault();if($(this).parents(".popup-comp-gallery")){var slider=$(this).parents(".popup-comp-gallery").find(".slider-gallery-detail");
if(slider.hasClass("slick-initialized")){initGalleryDetail.slick("unslick");slider.html("")}var popup=$(this).parents(".popup-comp-gallery").attr("id");setTimeout(function(){$("[data-popup-target='"+popup+"']").removeAttr("data-popup-target")},100)}});$(".gt-wrap").each(function(){var $this=$(this);var slide=$this.find(".gt-slide");setMainSlickDataOmni(slide,$this.data("cptnm"))});$(".wrap-component .btn-copy").each(function(){var url=getGrpBuySnsShareUrl();url+="?scrlLctn="+$(this).parent().parent().parent().parent().data("location");
$(this).attr("data-clipboard-text",url)});var clipboardCpt=new ClipboardJS(".wrap-component .btn-copy");clipboardCpt.on("success",function(e){var alertData={title:"",content:"링크가 복사되었습니다.",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert")});clipboardCpt.on("error",function(e){var alertData={title:"",content:"다시 시도하여 주십시오.",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert")});$(document).on("click",".wrap-component .btn-kakao",function(){var url=getGrpBuySnsShareUrl();
url+="?scrlLctn="+$(this).parent().parent().parent().parent().data("location");var imgpath=$(this).data("imgpath");var title="[공동구매] "+$(this).data("title");if(imgpath.startsWith("//"))imgpath="https:"+imgpath;var desc="판매가 "+$(this).data("sale-price")+"원\r\n→ 공동구매가 "+$(this).data("grpbuy-price")+"원";snsShare.kakaoTalk(url,title,imgpath,desc)})});function setMainSlickDataOmni(el,cptEnNm){var $this=$(el);var wrap=$this.parent();setSlickDataOmni(wrap,cptEnNm,"MAIN")}
function setPopSlickDataOmni(el,cptEnNm){setTimeout(function(){setSlickDataOmni(el,cptEnNm,"POP")},100)}
function setSlickDataOmni(el,cptEnNm,callDv){var btnPrev=el.find(".slick-prev");var btnNext=el.find(".slick-next");var dots=el.find(".slick-dots button");var btnPause=el.find(".slide-pause");var btnPlay=el.find(".slide-play");if(btnPrev.length>0)btnPrev.attr("data-omni",cptEnNm+":left_arrow");if(btnNext.length>0)btnNext.attr("data-omni",cptEnNm+":right_arrow");if(btnPause.length>0)btnPause.attr("data-omni",cptEnNm+" rolling:index_stop");if(btnPlay.length>0)btnPlay.attr("data-omni",cptEnNm+" rolling:index_play");
if(dots.length>0)for(var dotIdx=0;dotIdx<dots.length;dotIdx++)$(dots[dotIdx]).attr("data-omni",cptEnNm+" rolling:index_"+(dotIdx+1))}
function fnGetLastPrdPrice(goodsObjArr,stContextPath){var goodsIdArr=new Array;if(goodsObjArr!=null&&goodsObjArr.length>0){var goodsIdIdx=0;var idStrArr="";for(var idx=0;idx<goodsObjArr.length;idx++){idStrArr=$(goodsObjArr[idx]).attr("id").split("_");if(idStrArr.length==5&&idStrArr[3]!="")goodsIdArr[goodsIdIdx++]=idStrArr[3]}if(goodsIdArr.length==0)return false;$.ajax({data:JSON.stringify({goodsIdArr:goodsIdArr}),type:"POST",contentType:"application/json",url:stContextPath+"xhr/display/componentGoodsPrice",
success:function(data){if(data.result!=null&&data.result.length>0)data.result.forEach(function(item){if(item.lastPrice!=""){$("[id$="+item.goodsId+"_prclbl]").text(item.lastPrcLbl);$("[id$="+item.goodsId+"_price]").text(item.lastPrice+" 원")}})}})}return true}function fnGetAllPrdPrice(goodsObjArr,stContextPath){fnGetAllPrdPrice2(goodsObjArr,stContextPath,"","")}
function fnGetAllPrdPrice2(goodsObjArr,stContextPath,lastPrcText,stGbCd){var goodsIdArr=new Array;if(goodsObjArr!=null&&goodsObjArr.length>0){var goodsIdIdx=0;var idStrArr="";var compNo="";for(var idx=0;idx<goodsObjArr.length;idx++){idStrArr=$(goodsObjArr[idx]).attr("id").split("_");if(idStrArr.length==4&&idStrArr[3]!=""){goodsIdArr[goodsIdIdx++]=idStrArr[3];compNo=idStrArr[1]}}if(goodsIdArr.length==0)return false;$.ajax({data:JSON.stringify({goodsIdArr:goodsIdArr,compNo:compNo}),type:"POST",contentType:"application/json",
url:stContextPath+"xhr/display/componentGoodsPrice",success:function(data){if(data.result!=null&&data.result.length>0)data.result.forEach(function(item){if(item.prdPrice1!=""){$("[id$="+item.goodsId+"_prc1]").text(item.prdPrice1+" 원");$("[id$="+item.goodsId+"_lbl1]").text(item.prdPrcLbl1)}if(item.prdPrice2!=""){$("[id$="+item.goodsId+"_prc2]").text(item.prdPrice2+" 원");if(stGbCd=="90"&&lastPrcText!="")$("#slicePrdSel_"+compNo).find("[id$="+item.goodsId+"_lbl2]").text(lastPrcText);else $("[id$="+item.goodsId+
"_lbl2]").text(item.prdPrcLbl2)}if(item.prdPrice3!=""){$("[id$="+item.goodsId+"_prc3]").text(item.prdPrice3+" 원");if(lastPrcText!="")$("#slicePrdSel_"+compNo).find("[id$="+item.goodsId+"_lbl3]").text(lastPrcText);else $("[id$="+item.goodsId+"_lbl3]").text(item.prdPrcLbl3)}if(item.prdPrice4!=""){$("[id$="+item.goodsId+"_prc4]").text(item.prdPrice4+" 원");$("[id$="+item.goodsId+"_lbl4]").text(item.prdPrcLbl4)}if(item.membershipPoint!="")$("[id$="+item.goodsId+"_svmnt]").text(item.membershipPoint+"P")})}})}return true}
function fnGetPrdPrice(topId,arr,stContextPath){var topEl=topId;var goodsIdArr=arr;var childEl=$("#"+topEl).find(".prd-info[data-sideprd-prdcode-set]");if(childEl)childEl.each(function(i){var thisEl=$(this);var thisCode=thisEl.data("sideprd-prdcode-set");$.ajax({data:JSON.stringify({goodsIdArr:goodsIdArr}),type:"POST",contentType:"application/json",url:stContextPath+"xhr/display/componentGoodsPrice",success:function(data){if(data.result!=null&&data.result.length>0)data.result.forEach(function(item){for(var idx=
0;idx<goodsIdArr.length;idx++)if(item.goodsId==thisCode){thisEl.find(".prd-name").html(item.goodsNm);thisEl.find(".prd-code").html(item.mdlCode);thisEl.find(".reg .count").html(item.prdPrcLbl1);thisEl.find(".reg .price").html(item.prdPrice1+" 원");thisEl.find(".member .count").html(item.prdPrcLbl2);thisEl.find(".member .price").html(item.prdPrice2+" 원");if(item.prdPrice3){thisEl.find(".benefit .count").html(item.prdPrcLbl3);thisEl.find(".benefit .price").html(item.prdPrice3+" 원")}else thisEl.find(".benefit").remove();
thisEl.find(".card-btn a").attr("href","/sec/"+item.goodsPath)}})}})});return true}
function fnGetPrdPriceItr(topId,arr,stContextPath){var topEl=topId;var goodsIdArr=arr;var childEl=$("#"+topEl).find(".interior-txt[data-interior-prdcode-set]");if(childEl)childEl.each(function(i){var thisEl=$(this);var thisCode=thisEl.data("interior-prdcode-set");$.ajax({data:JSON.stringify({goodsIdArr:goodsIdArr}),type:"POST",contentType:"application/json",url:stContextPath+"xhr/display/componentGoodsPrice",success:function(data){if(data.result!=null&&data.result.length>0)data.result.forEach(function(item){for(var idx=
0;idx<goodsIdArr.length;idx++)if(item.goodsId==thisCode){thisEl.find(".prd-tit").html(item.goodsNm);thisEl.find(".prd-code").html(item.mdlCode);thisEl.find(".reg .count").html(item.prdPrcLbl1);thisEl.find(".reg .price").html(item.prdPrice1+" 원");thisEl.find(".member .count").html(item.prdPrcLbl2);thisEl.find(".member .price").html(item.prdPrice2+" 원");if(item.prdPrice3){thisEl.find(".benefit .count").html(item.prdPrcLbl3);thisEl.find(".benefit .price").html(item.prdPrice3+" 원")}else thisEl.find(".benefit").remove();
thisEl.parent(".prd-href").attr("href","/sec/"+item.goodsPath)}})}})});return true}
function downloadFileCms(lettNo){var fileInfo;var options={url:"/sec/business/xhr/insights/getFileInfoCms",data:{lettNo:lettNo},async:false,done:function(data){fileInfo=data}};ajax.call(options);if(fileInfo==undefined){var alertData={title:"",content:"파일이 존재하지 않습니다.",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return}var cnsntYn=$.cookie("cnsntYn");var link=document.location.pathname;console.log(link);if(cnsntYn=="Y")if(fileInfo.downYn=="Y")if(fileInfo.file.orgFlNm==
""){var alertData={title:"",content:"파일이 존재하지 않습니다.",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert")}else{var data={filePath:fileInfo.file.phyPath,fileName:fileInfo.file.orgFlNm};createFormSubmit("fileDownload","/sec/business/common/fileDownloadResult/",data)}else window.open(fileInfo.url,"_blank");else{$("#popupIdentificationCms div.cont > img").attr("src",fileInfo.letter.imgPath);$("#popupIdentificationCms div.cont > img").attr("alt",fileInfo.letter.ttl);$("#popupIdentificationCms div.cont > p").text(fileInfo.letter.ttl);
$("#popupIdentificationCms .login").attr("href","/sec/business/member/indexLogin/?returnUrl="+link);if(fileInfo.email=="")$("#email-identification-cms").val("");else{$("#email-identification-cms").val(fileInfo.email);$("#popupIdentificationCms #email-identification-cms").attr("disabled","disabled");$("#popupIdentificationCms .btn-box").hide();$("#popupIdentificationCms .error-msg > p").text("비즈니스 정보 열람/구독 신청을 진행해 주세요.");$("#email-identification-cms").addClass("error")}$("#checkCmsFileBtn").data("lett-no",
fileInfo.letter.lettNo);$("#checkCmsFileBtn").trigger("click");return false}}
function checkEmailCms(){var email=$("#email-identification-cms").val().trim();if(email==""){$("#popupIdentificationCms .error-msg > p").text("이메일을 입력해 주세요.");$("#email-identification-cms").addClass("error")}else if(!valid.email.test(email)){$("#popupIdentificationCms .error-msg > p").text("이메일을 정확히 입력해 주세요.");$("#email-identification-cms").addClass("error")}else{var checkYn=checkNewsletterYnCms(email);$.cookie("cnsntYn",checkYn);if(checkYn=="Y"){closeLayer("popupIdentificationCms");var lettNo=$("#checkCmsFileBtn").data("lett-no");
downloadFileCms(lettNo)}else{$("#popupIdentificationCms .error-msg > p").text("수신동의된 이메일이 아닙니다.");$("#email-identification-cms").addClass("error")}}}function checkNewsletterYnCms(email){var checkYn="";var options={url:"/sec/business/xhr/insights/checkNewsletterYn",data:{email:email},async:false,done:function(data){checkYn=data.checkYn}};ajax.call(options);return checkYn}
function cartDirect(mdlCode){var mdlList=[];var mdl={};mdl.mdlCode=mdlCode;mdl.qty=1;mdlList.push(mdl);fnCartDirect(mdlList,"confirm")}
function goGoodsInfo(mdlCode,ctaMoveStyleClassNm,ctaWindowStyleClassNm,goodsPath){if(ctaMoveStyleClassNm=="2")buyDirect(mdlCode,ctaWindowStyleClassNm);else if(ctaMoveStyleClassNm=="1")openCtaLink(goodsPath,ctaWindowStyleClassNm);else if(ctaMoveStyleClassNm=="3"||ctaMoveStyleClassNm=="5")openCtaLink(goodsPath,ctaWindowStyleClassNm);else if(ctaMoveStyleClassNm=="4")cartDirect(mdlCode)}
function adbrixInit(){if(typeof window!=="undefined"&&!window.adbrix){var adbrix={queue:[]};var userAgent=navigator.userAgent.toLowerCase();var script=document.createElement("script");var scriptName="Netscape"===navigator.appName&&-1!==navigator.userAgent.search("Trident")||-1!==userAgent.indexOf("msie")?"abx-web-sdk.ie.min.js":"abx-web-sdk.min.js";script.type="text/javascript";script.async=true;script.src="//static.adbrix.io/web-sdk/latest/"+scriptName;script.onload=function(){if(adbrix.runQueuedFunctions)adbrix.runQueuedFunctions();
else console.log("[adbrix] Error: could not load SDK")};var firstScript=document.getElementsByTagName("script")[0];firstScript.parentNode.insertBefore(script,firstScript);["init","onInitialized","login","getUserId","logout","userProperty.get","userProperty.getAll","userProperty.addOrUpdate","userProperty.remove","userProperty.removes","common.signUp","common.invite","common.useCredit","common.purchase","event.send","debug.traceListener","commerceAttr.categories","commerceAttr.product","commerce.viewHome",
"commerce.categoryView","commerce.productView","commerce.addToCart","commerce.addToWishList","commerce.reviewOrder","commerce.refund","commerce.search","commerce.share","commerce.listView","commerce.cartView","commerce.paymentInfoAdded","game.tutorialComplete","game.characterCreated","game.stageCleared","game.levelAchieved"].forEach(function(funcName){var funcNames=funcName.split(".");var funcNameToCall=funcNames.pop();funcNames.reduce(function(obj,name){return obj[name]=obj[name]||{}},adbrix)[funcNameToCall]=
function(){adbrix.queue.push([funcName,arguments])}});window.adbrix=adbrix;window.adbrix.init({appkey:"0nCtQ3s60km0zcXUGeZZBQ",webSecretkey:"IU54Ulr2xUawNnSUwBHrkw"})}}
function callAdbrix(mdlCode,goodsNm,prdPrice1,lastPrice,ctgDepth){if(stGbCd!=10&&stGbCd!=122)return;var ctgDepthArr=ctgDepth.split(" > ");var adbrixProductId=mdlCode;var adbrixProductName=goodsNm;var adbrixProductPrice=parseInt(prdPrice1.replace(/,/g,""));var adbrixProductDiscount=adbrixProductPrice-parseInt(lastPrice.replace(/,/g,""));var adbrixProductQuantity=1;var adbrixProductCategory=ctgDepthArr[0];var adbrixProductCategorySub=ctgDepthArr[1];if(window.secapp==undefined&&window.secapppopup==undefined){adbrixInit();
console.log(window.adbrix);console.log(adbrix);adbrix.onInitialized(function adbrixInitialized(){var product=adbrix.commerceAttr.product(adbrixProductId,adbrixProductName,adbrixProductPrice,adbrixProductQuantity,adbrixProductDiscount,"KRW",adbrix.commerceAttr.categories(adbrixProductCategory,adbrixProductCategorySub));var products=[];products.push(product);adbrix.commerce.addToCart(products);console.log("addToCart 호출 성공")})}else{var adbrixEventParam={};var adbrixProduct={};var adbrixProductList=[];
adbrixProduct.productId=adbrixProductId;adbrixProduct.productName=adbrixProductName;adbrixProduct.price=adbrixProductPrice;adbrixProduct.discount=adbrixProductDiscount;adbrixProduct.quantity=adbrixProductQuantity;adbrixProduct.category=adbrixProductCategory;adbrixProduct.categorySub=adbrixProductCategorySub;adbrixProductList.push(adbrixProduct);adbrixEventParam.productList=adbrixProductList;var adbrixEventParamJsonStr=JSON.stringify(adbrixEventParam);window.secapp.addToCart(adbrixEventParamJsonStr)}}
function showCarouselCountdown(targetId,timerId,dt,hr,mn){try{var _second=1E3;var _minute=_second*60;var _hour=_minute*60;var _day=_hour*24;var date=dt.split("-");var targetDate=new Date(Number(date[0]),Number(date[1])-1,Number(date[2]),Number(hr),Number(mn));var now=(new Date).getTime();var distDt=targetDate.getTime()-now;var htmlText="";var days="00";var hours="00";var minutes="00";var seconds="00";if(distDt<0){clearInterval(timerId);$("#"+targetId).remove()}else{days=Math.floor(distDt/_day);days=
days<10?"0"+days:days;hours=Math.floor(distDt%_day/_hour);hours=hours<10?"0"+hours:hours;minutes=Math.floor(distDt%_hour/_minute);minutes=minutes<10?"0"+minutes:minutes;seconds=Math.floor(distDt%_minute/_second);seconds=seconds<10?"0"+seconds:seconds;htmlText+="<ul>";htmlText+="\t<li>";htmlText+='\t\t<div class="num">'+days+'<span class="txt">일</span></div>';htmlText+="\t</li>";htmlText+="\t<li>";htmlText+='\t\t<div class="num">'+hours+'<span class="txt">시간</span></div>';htmlText+="\t</li>";htmlText+=
"\t<li>";htmlText+='\t\t<div class="num">'+minutes+'<span class="txt">분</span></div>';htmlText+="\t</li>";htmlText+="\t<li>";htmlText+='\t\t<div class="num">'+seconds+'<span class="txt">초</span></div>';htmlText+="\t</li>";htmlText+="</ul>";$("#"+targetId).html(htmlText)}}catch(e){clearInterval(timerId)}}
function downloadCoupon(stContextPath,cpNo,mdlCode){$.ajax({url:stContextPath+"xhr/coupon/goods/download",type:"POST",async:false,data:{cpNoList:cpNo},success:function(result){if(result.resultCode==="S"||result.exCode==="COP0009"||result.exCode==="COP0011")cartDirect(mdlCode);else{var callbackFunction="";if(result.exCode=="COP0024")callbackFunction=function(){window.location.href=$(".stPathTemp").eq(0).val()+"member/indexLogin/?returnUrl="+window.location.pathname+window.location.search};var alertData=
{title:"",content:result.exMsg,callback:callbackFunction,btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");return}}})}
function enterGroupBuy(stContextPath,grpBuyNo,obj){$.ajax({url:stContextPath+"xhr/enterGroupBuy",type:"POST",async:false,data:{grpBuyNo:grpBuyNo},success:function(data){if(data.isLogin){var alertData={title:"",content:data.resultMsg,callback:"",btnText:"확인"};if(data.success)fnGetGrpPrdCardForComponent(obj);commonAlert(alertData);openLayer("commonAlert");return}else{var alertData={title:"",content:"로그인이 필요합니다.",callback:function(){window.location.href=$(".stPathTemp").eq(0).val()+"member/indexLogin/?returnUrl="+
window.location.pathname+window.location.search},btnText:"확인"};commonAlert(alertData);openLayer("commonAlert")}}})}function getParam(name){var curr_url=location.search.substr(location.search.indexOf("?")+1);var svalue="";if(curr_url!=""){var params=curr_url.split("&");for(var i=0;i<params.length;i++){var temp=params[i].split("=");if(temp[0]==name)svalue=temp[1]}}return svalue}
function getGrpBuySnsShareUrl(){var url=window.location.href.substr(0,window.location.href.indexOf("?"));if(url=="")url=window.location.href;return url}
function navigationBar(){var targetElement=$(".type-visual");var targetSlide=targetElement.find(".navigation");var navVisual=true;function checkWidth(){$(".navigation").each(function(){var sum=0;var _this=$(this);var navW=_this.outerWidth(true);var settings={slidesPerView:"auto",slideToClickedSlide:false,navigation:{nextEl:_this.find(".btn-next"),prevEl:_this.find(".btn-prev")},centeredSlides:true,centeredSlidesBounds:true,breakpoints:{801:{centeredSlides:false,centeredSlidesBounds:false}}};_this.find(".item").each(function(index){sum+=
parseInt($(this).outerWidth(true),10)});if(sum>navW)if(_this.hasClass("swiper-container-initialized"))_this.data("slider").updateSlides();else{slider=new Swiper(_this,settings);_this.data("slider",slider);_this.find(".nav-slider").css("justify-content","flex-start")}else if(_this.hasClass("swiper-container-initialized")){_this.data("slider").destroy();_this.removeData("slider");_this.find(".swiper-wrapper").removeAttr("style");_this.find(".swiper-slide").removeAttr("style");_this.find(".nav-slider").removeAttr("style")}})}
function navFixed(){var navType=$(".navigation").parent().parent().parent();if(navType.hasClass("type-visual")){var targetTop=$(".type-visual").offset().top;var targetTopNum=parseInt(targetTop)}else var targetTop=0;if(navType.hasClass("type-visual"))$(window).scroll(function(){if(targetTopNum<=$(window).scrollTop()&&navVisual==true){targetElement.removeClass("type-visual");targetElement.addClass("fixed");checkWidth();moveLine();if(targetSlide.hasClass("swiper-container-initialized")){targetSlide.data("slider").updateSlides();
targetSlide.data("slider").slideTo(0,0)}navVisual=false}else if(targetTopNum>$(window).scrollTop()&&navVisual==false){targetElement.addClass("type-visual");targetElement.removeClass("fixed");checkWidth();if(targetSlide.hasClass("swiper-container-initialized")){targetSlide.data("slider").updateSlides();targetSlide.data("slider").slideTo(0,0)}navVisual=true}else return false})}function moveLine(){var nav=$(".navigation-bar .navigation");var menu=nav.find(".item");var pos=0;var wid=0;nav.each(function(){var _this=
$(this);var active=_this.find(".active");var pos=active.position();var wid=active.width();var menu=_this.find(".item");var bar=_this.find(".line");if(active.length)bar.css({left:pos.left,width:wid});menu.mouseleave(function(e){if(active.length)bar.css({left:pos.left,width:wid})})});menu.mouseover(function(e){var _this=$(this).find("a");var bar=_this.parent().parent().find(".line");var position=_this.position();var width=_this.width();bar.css({left:position.left,width:width})})}checkWidth();navFixed();
moveLine()}
function filterSel(){$(".filter-slick:not(.event)").each(function(){$(this).addClass("event");var _this=$(this);var check=_this.find("input:checked");var checkIdx=0;if(check.parent().index()>0)checkIdx=check.parent().index();if(_this.width()>_this.parent().width()){_this.parent().addClass("slideOn");var slider=new Swiper(_this,{slidesPerView:"auto",slideToClickedSlide:true,initialSlide:check.parent().index(),navigation:{nextEl:_this.find(".btn-next"),prevEl:_this.find(".btn-prev")},spaceBetween:5,breakpoints:{801:{spaceBetween:8},
1441:{spaceBetween:10}}});slider.slideTo(checkIdx)}})}
function fnGetMdPickForComponent(obj){var goodsId=$(obj).data("goods-id");var orgGoodsId=$(obj).data("org-goods-id");var targetId=$(obj).data("target-id");var componentId=$(obj).data("component-id");var stContextPath=$(obj).data("st-context-path");var svmnAmtDispYn=$(obj).data("svmn-amt-disp-yn");var lastPrcText=$(obj).data("last-prc-text");var ctaMoveStyle=$(obj).data("cta-move-style");var ctaWindowStyleClassNm=$(obj).data("cta-window-style-class-nm");var bgColor=$(obj).data("bg-color");if($(obj).prop("checked")||
!$(obj).hasClass("focused")&&!$(obj).hasClass("disabled"))$.ajax({url:stContextPath+"xhr/display/componentGoodsForMdPick",type:"POST",data:{goodsId:goodsId,targetId:targetId,svmnAmtDispYn:svmnAmtDispYn,lastPrcText:lastPrcText,ctaMoveStyle:ctaMoveStyle,ctaWindowStyleClassNm:ctaWindowStyleClassNm,bgColor:bgColor,orgGoodsId:orgGoodsId},success:function(data){if(data.html!=null&&data.html!=""){$("#"+data.targetId).html(data.html);var observer=lozad();observer.observe()}$("#"+componentId+" .card-images").each(function(){$(this).height($(this).outerWidth())});
listHeightControl("#"+componentId,".box-product-card");$(window).scrollTop($("#"+targetId).offset().top);filterSel();colorOptSel()}})}
function fnGetGrpBuyList(){var stContextPath=$("#viewStContextPath").val();var grpBuyNo="";var grpBuyNos=[];var goodsIds=[];$("[name=grpBuyInfo]").each(function(){if(!$(this).children(".count-bar-box").hasClass("success")){grpBuyNo=$(this).data("grpbuyno");if(grpBuyNo!=undefined)grpBuyNos.push(grpBuyNo);goodsId=$(this).data("goodsid");if(goodsId!=undefined)goodsIds.push(goodsId)}});grpBuyNos=Array.from(new Set(grpBuyNos));goodsIds=Array.from(new Set(goodsIds));grpBuyNos=grpBuyNos.sort();goodsIds=
goodsIds.sort();if(grpBuyNos.length>0||goodsIds.length>0){var options={url:stContextPath+"xhr/display/getGrpBuyListAjax",data:{grpBuyNos:grpBuyNos,goodsIds:goodsIds},done:function(data){var grpBuyList=data.grpBuyList;var stContextPath=$("#viewStContextPath").val();for(var i in grpBuyList){var grpBuy=grpBuyList[i];var grpBuyNo=grpBuy.grpBuyNo;var goodsId=grpBuy.goodsId;var divGrpBuy=$("[name=grpBuyInfo][data-grpbuyno="+grpBuyNo+"][data-goodsid="+goodsId+"]");var compNo=$(divGrpBuy).data("compno");
var grpBuyIndex=$(divGrpBuy).data("grpbuyindex");var grpBuyId=grpBuyNo+"_"+goodsId;grpBuy.joinCnt=Number(grpBuy.joinCnt);grpBuy.trgtQty=Number(grpBuy.trgtQty);$("[name=goodsNm_"+grpBuyId+"]").text(grpBuy.goodsNm);$("[name=mdlCode_"+grpBuyId+"]").text(grpBuy.mdlCode);$("[name=trgtQty_"+grpBuyId+"]").text(grpBuy.trgtQty);$("[name=countBarBox_"+grpBuyId+"]").removeClass("success");if(grpBuy.joinCnt<grpBuy.trgtQty){$("[name=prgBar_"+grpBuyId+"]").css("width",grpBuy.joinCnt/grpBuy.trgtQty*100+"%");if(grpBuy.joinCnt==
0)$("[name=barTxt_"+grpBuyId+"]").text("신청 시작!");else $("[name=barTxt_"+grpBuyId+"]").html("<span class='num'>"+(grpBuy.trgtQty-grpBuy.joinCnt)+"</span>명만 더!")}else{$("[name=countBarBox_"+grpBuyId+"]").addClass("success");$("[name=barTxt_"+grpBuyId+"]").text("공동구매 성공!");$("[name=prgBar_"+grpBuyId+"]").css("width","100%")}$("[name=prdPrice1_"+grpBuyId+"]").text(grpBuy.prdPrice1);$("[name=grpPrice_"+grpBuyId+"]").text(fnComma(grpBuy.salePrice-grpBuy.cpDcAmt));$("[name=salePsbQty_"+grpBuyId+"]").text(grpBuy.salePsbQty);
$("[name=tagBox01_"+grpBuyId+"]").removeClass("success");if(grpBuy.joinCnt>=grpBuy.trgtQty)$("[name=tagBox01_"+grpBuyId+"]").addClass("success");var ctaHtml="";$("[name=grpBtn_"+grpBuyId+"]").remove();if(grpBuy.grpBuySaleStatCd=="20")ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type2 disable'>판매 준비중</button>";else if(grpBuy.saleStatCd!="12")ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type2 disable'>선착순 판매 종료</button>";else if(grpBuy.ingYn!=
"Y")ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type2 disable'>공동구매가 "+"<span>"+fnComma(grpBuy.salePrice-grpBuy.cpDcAmt)+"</span>원 "+"</button>";else if(grpBuy.joinCnt>=grpBuy.trgtQty)ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type3' "+"onclick=\"downloadCoupon('"+stContextPath+"',"+grpBuy.cpNo+",'"+grpBuy.mdlCode+"');\"> "+"공동구매가 <span>"+fnComma(grpBuy.salePrice-grpBuy.cpDcAmt)+"</span>원 "+"</button>";else if(grpBuy.mbrJoinCnt>
0)ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type2 disable' onclick='appliedGrpBuy();'>신청 완료</button>";else ctaHtml="<button name='grpBtn_"+grpBuyId+"' type='button' class='btn btn-d btn-type2 hvr-pulse' "+"onclick=\"enterGroupBuy('"+stContextPath+"', "+grpBuyNo+', this);" '+"data-goods-id='"+goodsId+"' "+"data-target-id='prdSel_"+compNo+"_"+grpBuyIndex+"' "+"data-component-id='slicePrdSel_"+compNo+"' "+"data-st-context-path='"+stContextPath+"' "+"data-group-buy-no='"+
grpBuyNo+"'>공동구매 신청하기"+"</button>";$("[name=grpBtns_"+grpBuyId+"]").prepend(ctaHtml);$("[name=aplPntAmt_"+grpBuyId+"]").empty();if(grpBuy.aplPntAmt1!=null&&grpBuy.aplPntAmt1!=""&&Number(grpBuy.aplPntAmt1)>0||grpBuy.aplPntAmt2!=null&&grpBuy.aplPntAmt2!=""&&Number(grpBuy.aplPntAmt2)>0){var pointTxt="";pointTxt+="<div class='point-txt'>";if(grpBuy.aplPntAmt1!=""&&Number(grpBuy.aplPntAmt1)>0)pointTxt+="<p>삼성카드 금액대별 결제일할인 <span>"+fnComma(grpBuy.aplPntAmt1)+"P</span></p>";if(grpBuy.aplPntAmt2!=""&&Number(grpBuy.aplPntAmt2)>
0)pointTxt+="<p>다다익선 포인트 <span>"+fnComma(grpBuy.aplPntAmt2)+"P</span></p>";pointTxt+="</div>";$("[name=aplPntAmt_"+grpBuyId+"]").html(pointTxt)}$("[name=goodsDscrt_"+grpBuyId+"]").empty();if(grpBuy.goodsDscrt1!=null&&grpBuy.goodsDscrt1!=""||grpBuy.goodsDscrt2!=null&&grpBuy.goodsDscrt2!=""){var dscrtTxt="";dscrtTxt+="<ul class='li-dot'>";if(grpBuy.goodsDscrt1!=null&&grpBuy.goodsDscrt1!="")dscrtTxt+="<li>"+grpBuy.goodsDscrt1+"</li>";if(grpBuy.goodsDscrt2!=null&&grpBuy.goodsDscrt2!="")dscrtTxt+="<li>"+
grpBuy.goodsDscrt2+"</li>";dscrtTxt+="</ul>";$("[name=goodsDscrt_"+grpBuyId+"]").html(dscrtTxt)}}}};ajax.call2(options)}};
