var eventInfo;var entryEvent;var collectItems;var goodsSerialInfos;var plcyContentCollect;var plcyContentPrcs;var eventPrivacyPolicys;var addFields;var plazas;var siDoList;var siGunGuList;var questionInfos;var sessionMbr;var membershipNo;var stPath;var returnUrl;var pblcEvtNo;var eventGbCd;var kakaoAppKeyEvent;var siDo10;var siGunGu123;var isPreView=false;var oneTimeChk=false;var plazaNm;var $popDiv;var $tooltipDiv;$(function(){$popDiv=$(drawPopHtmlCode());$tooltipDiv=$(drawTooltipHtmlCode())});
function fnDrawPop(){if($("#popupArea_Event3791").length>0)$("#popupArea_Event3791").append($popDiv);else $("#popupArea").append($popDiv);if($("#tooltipArea_Event3791").length>0)$("#tooltipArea_Event3791").append($tooltipDiv);else $("#tooltipArea").append($tooltipDiv);$(".titleNo").show()}
function fnScriptLoad(){$.getScript("//developers.kakao.com/sdk/js/kakao.min.js").done(function(script,textStatus){}).fail(function(jqxhr,settings,exception){});$.getScript("//dapi.kakao.com/v2/maps/sdk.js?appkey="+kakaoAppKeyEvent+"&autoload=false",function(){daum.maps.load(function(){fnEventReservationJsLoad()})})}
function fnEventReservationJsLoad(){var def=$.Deferred();var script=document.createElement("script");script.src="/sec/static/_script/event/event-reservation.js?ver=1.4";script.onload=function(){def.resolve()};script.onerror=function(){def.reject()};document.body.appendChild(script)}
function fnCallPop2(evtNo){oneTimeChk=false;pblcEvtNo=evtNo;returnUrl=window.location.pathname;var searchPath=window.location.search;if(searchPath.indexOf("eventNo")!=-1)returnUrl+=searchPath;else if(searchPath.indexOf("?")!=-1)if(returnUrl.indexOf("event/eventContentDetailView")!=-1)returnUrl+=searchPath+"&eventNo="+pblcEvtNo;else returnUrl+=searchPath;else returnUrl+="?eventNo="+pblcEvtNo;stPath=$("#openPop").data("st-path");var param;param={eventNo:pblcEvtNo,isPreView:isPreView};var options={url:stPath+
"xhr/event/getEventBaseInfo",data:param,done:function(data){$("#mask").remove();var eventInfo=data.eventInfo;kakaoAppKeyEvent=data.kakaoAppKey;siDo10=data.siDo10;siGunGu123=data.siGunGu123;if(eventInfo.errMsg==""||eventInfo.errMsg==null)setEventPop(data);else if(eventInfo.errCd=="LGN0005")makeAlert(eventInfo.errMsg,fnGoLoginPage);else makeAlert(eventInfo.errMsg,eventPopClose);if(eventInfo.plazas)$("#eventBtn_Area_div").css("display","none");else $("#eventBtn_Area_div").css("display","")}};ajax.call(options)}
function setEventPop(data){fnDrawPop();$("#exhibition").click();eventInfo=data.eventInfo;entryEvent=eventInfo.entryEvent;collectItems=eventInfo.eventCollectItems;goodsSerialInfos=eventInfo.goodsSerialInfos;plcyContentCollect=eventInfo.plcyContentCollect;plcyContentPrcs=eventInfo.plcyContentPrcs;eventPrivacyPolicys=eventInfo.eventPrivacyPolicys;addFields=eventInfo.addFields;questionInfos=eventInfo.questionInfos;plazas=eventInfo.plazas;siDoList=eventInfo.siDoList;siGunGuList=eventInfo.siGunGuList;$("#entryEventNo").val(entryEvent.eventNo);
$("#evtGbCd").val(entryEvent.eventGbCd);$("#prtcpPsbGbCd").val(entryEvent.prtcpPsbGbCd);$("#prtcpPsbCnt").val(entryEvent.prtcpPsbCnt);$("#evtNm").text(entryEvent.ttl);$("#cpNo").val(entryEvent.cpNo);$("#ftEvtNm").text(entryEvent.ttl);$("#eventAddYn").val(entryEvent.eventAddYn);sessionMbr=eventInfo.loginUserMbrNo;membershipNo=eventInfo.loginUserMembership;eventGbCd=entryEvent.eventGbCd;setLayoutShowHide(eventGbCd);setCommLayout(entryEvent,collectItems,addFields);if(eventGbCd=="40"){$(".goodsSelect").hide();
$("#goodsUl").empty();$("#biztalkUseYn").val(entryEvent.biztalkUseYn);$("#biztalkTmplTxt").val(entryEvent.biztalkTmplTxt)}if(eventGbCd=="50"){$(".goodsSelect").hide();$("#goodsUl").empty();var html="";$.each(goodsSerialInfos,function(idx,val){var index=idx+1;html+='<li class="item">';html+='\t<input id="chk-goods-'+index+'" type="radio" name="chk-goods" value="'+val.goodsId+"\" onchange='goodsCheck(this)' data-mdlcode='"+val.mdlCode+"' data-goods-nm='"+val.goodsNm+"'>";html+='\t<label for="chk-goods-'+
index+'">'+val.mdlCode+"</label>";html+="</li>"});$("#goodsUl").append(html);$(".goodsSelect").show();$("#inpEnterSerialNum").attr("readonly",true)}if(eventGbCd=="60")createQuestionHtml(questionInfos);if(eventGbCd=="80"){fnScriptLoad();$("#biztalkTmplTxt").val(entryEvent.biztalkTmplTxt)}var policyHtml="";$("#privacyPolicy").empty();policyHtml+=createPrivacyPolicyHtml(plcyContentCollect,1);policyHtml+=createPrivacyPolicyHtml(plcyContentPrcs,2);$.each(eventPrivacyPolicys,function(idx,val){var index=
idx+3;policyHtml+=createPrivacyPolicyHtml(val,index)});$("#privacyPolicy").append(policyHtml);$(".error-msg").hide();if($("#eventAddYn").val()=="N")$("#inpCounselMembershipErr").html("<p>나의 정보에서 멤버십 회원 추가정보 입력 후</p><p>알림신청하면 멤버십 번호가 보여집니다.</p>");else if($("#eventAddYn").val()=="Y")$("#inpCounselMembershipErr").html("<p>※멤버십번호가 보이지 않으시나요?</p><p>화면 우측 상단 > 나의정보 메뉴에서</p><p>멤버십 가입여부 확인 후 다시 시도해 보세요.</p><p>(미가입 시 가입 후 재시도 필요)</p>");if(membershipNo==""||membershipNo==null)$("#inpCounselMembershipErr").show()}
function goodsCheck(obj){$("#inpEnterSerialNum").attr("readonly",false)}
function createPrivacyPolicyHtml(obj,index){var agreeRqidYn=obj.agreeRqidYn;var agreeRqidYnNm;var agreeSelWds=obj.agreeSelWds;var policyNo=obj.policyNo;if(agreeRqidYn=="Y")agreeRqidYnNm="필수";else agreeRqidYnNm="선택";if(obj.plcyGbCd=="10")agreeSelWds="위의 개인정보 수집 및 이용에 동의합니다.";else if(obj.plcyGbCd=="20")agreeSelWds="위의 개인정보 처리 업무 위탁에 동의합니다.";var html="";html+="<div class='terms-wrap'>";html+="\t<h4 class='terms-tit'>"+obj.plcyNm+"</h4>";html+="\t<div class='terms-box'>";html+="\t\t<p>"+obj.content+"</p>";
html+="\t</div>";html+="\t<div class='chk-form terms-more'>";if(agreeRqidYn=="Y")html+="\t\t<input id='chk-enter-"+index+"' data-chkgrp-name='checkEventEnter' type='checkbox' required='' title='' class='inp-terms entryAgreeY plcyGbCd"+obj.plcyGbCd+"' data-policyNo="+policyNo+">";else html+="\t\t<input id='chk-enter-"+index+"' data-chkgrp-name='checkEventEnter' type='checkbox' required='' title='' class='inp-terms plcyGbCd"+obj.plcyGbCd+"' data-policyNo="+policyNo+">";if(obj.plcyGbCd!="20")html+="\t\t<label for='chk-enter-"+
index+"' class='chk-gray'>"+agreeSelWds+" ("+agreeRqidYnNm+")</label>";html+="\t</div>";if(agreeRqidYn=="Y"&&obj.plcyGbCd!="20"){html+="\t<div class='error-msg' id='err-chk-enter-"+index+"'>";if(obj.plcyGbCd=="10")html+="\t\t<p>개인정보 수집 및 이용에 동의해 주세요.</p>";else html+="\t\t<p>"+obj.plcyNm+"에 동의해 주세요.</p>";html+="\t</div>"}html+="</div>";return html}
function createQuestionHtml(obj){$(".qstList").empty();var html="";$.each(questionInfos,function(idx,val){var qstTpCd=val.qstTpCd;var rplContent=val.rplContent;var rplNos=val.rplNos;var rghtansYn=val.rghtansYn;var qstNo=val.qstNo;html+="<div class='survey-item'>";html+="    <p class='question'>Q. "+val.qstNm+"</p>";html+="    <input type='hidden' id='qstAnswer"+qstNo+"' name='qstAnswer' value='N' data-qsttpcd='"+qstTpCd+"'/>";html+="    <div class='answer-box'>";if(qstTpCd=="30"){html+="        <input type='text'  id='answer"+
qstNo+"' name='answer"+qstNo+"' class='inp-line qstAnswer"+qstNo+"' placeholder='정답을 입력해 주세요.' maxlength='200'>";html+="        <input type='hidden' id='answer"+qstNo+"Y' name='answer"+qstNo+"Y' value='"+rplContent+"'/>"}else{html+="        <ul class='answer-list chk-form qstAnswer"+qstNo+"'>";var rplNosArr=rplNos.split(",");var rplContentArr=rplContent.split(",");var rghtansYnArr=rghtansYn.split(",");for(var i=0;i<rplNosArr.length;i++){var qNo=rplNosArr[i];var qText=rplContentArr[i];var qAns=rghtansYnArr[i];
html+="            <li class='item'>";if(qstTpCd=="10")html+="            <input id='answer"+qstNo+qNo+"' type='checkbox' name='answer"+qstNo+"' value='Y'>";else if(qstTpCd=="20")html+="            <input id='answer"+qstNo+qNo+"' type='radio' name='answer"+qstNo+"' value='Y'>";html+="                <label for='answer"+qstNo+qNo+"'>"+qText+"</label>";html+="                <input type='hidden' id='answer"+qstNo+qNo+"Y' value='"+qAns+"'/>";html+="            </li>"}html+="        </ul>"}html+="    </div>";
html+="\t <div style='width: 100%; display: inline-block;margin-top:20px'>";html+="\t     <div style='display:inline-block;vertical-align:middle;'>";if(qstTpCd=="30")html+="\t \t\t<button type='button' class='btn btn-s btn-type1 chkAns' style='margin-top:0' name='qstAnswer"+qstNo+"' id='chkAnsBtn"+qstNo+"' arg1='"+qstNo+"' arg2='"+qstTpCd+"'>정답확인</button>";else html+="\t \t\t<button type='button' class='btn btn-s btn-type1 chkAns' style='margin-top:0' id='chkAnsBtn"+qstNo+"' arg1='"+qstNo+"' arg2='"+
qstTpCd+"'>정답확인</button>";html+="\t     </div>";html+="\t     <div class='error-msg answer-msg' id='answer"+qstNo+"Err' style='display:inline-block;vertical-align:middle;margin-left:8px;padding-top:0'>";html+="\t       <p>오답입니다.</p>  ";html+="\t     </div>    ";html+="\t </div>\t";html+="</div>"});$(".qstList").append(html);$(".error-msg").hide();if(membershipNo==""||membershipNo==null)$("#inpCounselMembershipErr").show()}
function setLayoutShowHide(eventGbCd){$(".eventGbCd50").hide();$(".eventGbCd60").hide();$(".eventGbCd70").hide();$(".eventGbCd80").hide();$(".titleNo").hide();$("#eventSaveBtn").text("이벤트 응모");$("#popTitle").text("응모자 정보");$("#evtHeader h2").text("응모 하기");if(eventGbCd=="40"||eventGbCd=="50"){$("#popTitle").val("");$(".eventGbCd50").show()}else if(eventGbCd=="60"){$("#popTitle").val("");$(".eventGbCd60").show()}else if(eventGbCd=="70"){$("#eventSaveBtn").text("투표하기");$("#popTitle").text("투표자 정보");
$("#evtHeader h2").text("투표 하기");$(".eventGbCd70").show()}else if(eventGbCd=="80"){$(".titleNo").show();$(".eventGbCd80").show();$("#popTitle").text(entryEvent.ttl+" 매장상담예약 이벤트 신청정보")}$("#chk-enter-all").prop("checked",false);$("#inpEnterName").focus()}
function setCommLayout(entryEvent,collectItems,addFields){var imgUrl="";var filter="win16|win32|win64|mac|macintel";if(navigator.platform)if(filter.indexOf(navigator.platform.toLowerCase())<0)imgUrl="//"+entryEvent.moImgPath;else imgUrl="//"+entryEvent.pcImgPath;if(imgUrl=="")$("#evtHeader").removeClass("text-hide");else{$("#evtImg").attr("src",imgUrl);$("#evtHeader").addClass("text-hide")}if(sessionMbr==0||sessionMbr==null)$("#inpEnterName").removeAttr("readonly");if(sessionMbr!=0&&sessionMbr!=null){$("#inpEnterName").attr("readonly",
true);$("#inpEnterName").val(eventInfo.loginUserMbrNm);$("#inpEnterCall").val(eventInfo.loginUserMobile);$("#inpEnterEmail").val(eventInfo.loginUserEmail);$("#inpCounselMembership").val(membershipNo)}$(".entryCollect").hide();$.each(collectItems,function(idx,val){var collectItemCd=val.collectItemCd;$(".entryCollect"+collectItemCd).show()});if(membershipNo==""||membershipNo==null);$("#addFieldArea").empty();var addFieldHtml="";$.each(addFields,function(idx,obj){addFieldHtml+=createAddFieldHtml(obj)});
$("#addFieldArea").append(addFieldHtml)}
function createAddFieldHtml(obj){var fldTpCd=obj.fldTpCd;var fldNm=obj.fldNm;var fldVal=obj.fldVal;var fldNo=obj.fldNo;var fldDscrt=obj.fldDscrt;var html="";var divInpBox="<div class='inp-box'>";var labelFor="    <label for='addField"+fldNo+"' class='lb-line'>"+fldNm+"</label>";var comment="\t\t <p class='essential'>"+fldDscrt+"</p>";if(fldTpCd=="10"){html+=divInpBox;html+=labelFor;html+="    <div>";html+="        <input type='text' name='addField"+fldNo+"' id='addField"+fldNo+"' class='inp-line' value='' data-fldtpcd='"+
fldTpCd+"'>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="        \t<p>입력해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>"}else if(fldTpCd=="20"){html+=divInpBox;html+=labelFor;html+="    <div>";html+="        <div class='inquiry-con'>";html+="            <textarea name='addField"+fldNo+"' id='addField"+fldNo+"' class='inp-line pop-tArea' placeholder='입력해 주세요.' maxlength='500' data-fldtpcd='"+fldTpCd+"'></textarea>";html+=
"        </div>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="        \t<p>입력해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>\t"}else if(fldTpCd=="30"){html+=divInpBox;html+=labelFor;html+="    <div>";html+="        <ul class='chk-list-box chk-form mo-col2' id='addField"+fldNo+"' data-fldtpcd='"+fldTpCd+"'>";var fldValArrRd=fldVal.split(",");for(var i=0;i<fldValArrRd.length;i++){var lb=fldValArrRd[i];html+="            <li class='item'>";
html+="                <input id='addField"+fldNo+(i+1)+"' type='radio' name='addField"+fldNo+"' value='"+lb+"'>";html+="                <label for='addField"+fldNo+(i+1)+"'>"+lb+"</label>";html+="            </li>"}html+="        </ul>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="        \t<p>선택해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>"}else if(fldTpCd=="40"){html+=divInpBox;html+=labelFor;html+="    <div>";html+=
"        <ul class='chk-list-box chk-form mo-col2' id='addField"+fldNo+"' data-fldtpcd='"+fldTpCd+"'>";var fldValArrChk=fldVal.split(",");for(var j=0;j<fldValArrChk.length;j++){var lb2=fldValArrChk[j];html+="            <li class='item'>";html+="                <input id='addField"+fldNo+(j+1)+"' type='checkbox' name='addField"+fldNo+"' value='"+lb2+"'>";html+="                <label for='addField"+fldNo+(j+1)+"'>"+lb2+"</label>";html+="            </li>"}html+="        </ul>";if(fldDscrt!=null)html+=
comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="        \t<p>선택해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>"}else if(fldTpCd=="50"){html+=divInpBox;html+="    <label for='addField"+fldNo+"Btn' class='lb-line'>"+fldNm+"</label>";html+="    <div>";html+="        <div class='select-box'>";html+="            <div id='dropAge' class='wrap-droplist'>";html+="                <button type='button' class='droplist-button' aria-haspopup='listbox' aria-labelledby='addField"+
fldNo+"Btn' id='addField"+fldNo+"Btn'>선택해 주세요.</button>";html+="                <ul class='droplist' tabindex='-1' role='listbox' aria-labelledby='addField"+fldNo+"Btn' aria-activedescendant='addField"+fldNo+"1' id='addField"+fldNo+"' data-fldtpcd='"+fldTpCd+"'>";var fldValArrSel=fldVal.split(",");for(var k=0;k<fldValArrSel.length;k++){var lb3=fldValArrSel[k];html+="                <li id='addField"+fldNo+(k+1)+"' role='option' class='droplist-item'>"+lb3+"</li>"}html+="                </ul>";html+=
"            </div>";html+="        </div>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="        \t<p>선택해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>"}else if(fldTpCd=="60"){html+=divInpBox;html+=labelFor;html+="    <div>";html+="        <div class='box mail'>";html+="            <input type='text' id='addField"+fldNo+"' class='inp-line' title='파일첨부' readOnly='readOnly'>";html+="            <input type='hidden' id='phyPath"+
fldNo+"' name='phyPath"+fldNo+"' />";html+="            <button type='button' class='btn btn-s btn-type1' id='upldBtn"+fldNo+"60' onclick=\"fnSearchFile('"+fldNo+"')\">찾아보기</button>";html+="        </div>";html+="        <p class='essential'>* JPG, PNG 파일만 첨부 가능합니다.</p>";html+="        <ul class='addfile-list file-list"+fldNo+"'></ul>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+fldNo+"Err'>";html+="            <p>첨부된 파일이 없습니다.</p>";html+="    \t</div>";html+=
" \t\t<input type='hidden' name='fileExe"+fldNo+"'  id='fileExe"+fldNo+"'/>";html+=" \t\t<input type='hidden' name='fileName"+fldNo+"' id='fileName"+fldNo+"'/>";html+=" \t\t<input type='hidden' name='filePath"+fldNo+"' id='filePath"+fldNo+"'/>";html+=" \t\t<input type='hidden' name='fileSize"+fldNo+"' id='fileSize"+fldNo+"'/>";html+=" \t\t<input type='hidden' name='fileType"+fldNo+"' id='fileType"+fldNo+"'/>";html+="    </div>";html+="</div>"}else if(fldTpCd=="70"){fldVal="//"+fldVal;html+="<div>";
html+="    <label for='inpEnterFileImg' class='lb-line'>"+fldNm+"</label>";html+='    <div class="event-img">';html+="\t \t<img src='"+fldVal+"' style='width:100%; height:250px;'>";html+="    </div>";if(fldDscrt!=null)html+=comment;html+="</div>"}else if(fldTpCd=="80"){var html80="";html80="<div class='inp-txt-box'>";if(fldNm!=null)html80+="    <label for='addField"+fldTpCd+"' class='lb-line'>"+fldNm+"</label>";html80+="    <div class='pre-box'>";html80+="            <pre>"+fldVal+"</pre>";if(fldDscrt!=
null)html80+="            <pre>"+fldDscrt+"</pre>";html80+="    </div>";html80+="</div>";html=html80}else if(fldTpCd=="90"){html+=divInpBox;html+=labelFor;html+="    <div>";html+="        <div class='inquiry-con'>";html+="            <textarea name='addField"+fldNo+"' id='addField"+fldNo+"' class='inp-line pop-tArea' placeholder='입력해 주세요.' maxlength='500' data-fldtpcd='"+fldTpCd+"'></textarea>";html+="        </div>";if(fldDscrt!=null)html+=comment;html+="        <div class='error-msg' id='addField"+
fldNo+"Err'>";html+="        \t<p>입력해 주세요.</p>";html+="        </div>";html+="    </div>";html+="</div>\t"}return html}
function fnCheckSerialNo(){var goodsVal=$("input[name='chk-goods']:checked").val();var inputValue=$("#inpEnterSerialNum").val();$("#inpEnterSerialNumErr").hide();if(goodsVal==undefined||goodsVal==""){makeAlert("제품을 선택하셔야 시리얼 넘버 확인이 가능합니다.");return}if(inputValue==""){$("#inpEnterSerialNumErr").show();return}var param={serialNo:inputValue,mdlCode:$("input[name='chk-goods']:checked").data("mdlcode"),goodsId:$("input[name='chk-goods']:checked").val(),eventNo:pblcEvtNo};var options={url:stPath+"xhr/event/checkSerialNo",
data:param,type:"GET",done:function(data){var result=data.result;$("#serialNumChk").val(result.validate);if(result.validate=="Y"){$("#serialNum").val(result.serialNo);$("#mdlCode").val(result.mdlCode)}if(result.validate=="Y")makeAlert("제품 시리얼 넘버<br/>확인이 완료되었습니다.");else if(result.validate=="D"){makeAlert("이미 사용된 시리얼입니다.");$("#serialNumChk").val("N")}else makeAlert("제품 시리얼 넘버를 다시<br/>입력해 주세요.");if(result==="N")$("#inpEnterSerialNum").select()}};ajax.call(options)}
function fnGetReplyList(evtNo,so){if(evtNo==undefined||evtNo==""){makeAlert("eventNo가 존재하지 않습니다.");return}stPath=$("#openPop").data("st-path");var param={eventNo:evtNo,fldTpCd:"90",page:so!==undefined?so.page:1,rows:so!==undefined?so.rows:10};var options={url:stPath+"xhr/event/getReplyList",data:param,type:"POST",dataType:"html",done:function(data){$("#review-list").html(data)}};ajax.call(options)}
function checkAnswer(qstNo,qstTpCd){var rplCnt=0;var answerCnt=0;if(qstTpCd=="30"){var inputAnswer=$("input[name=answer"+qstNo+"]").val();var answer=$("input[name=answer"+qstNo+"Y]").val();if(inputAnswer==answer){$("#answer"+qstNo+"Err").hide();makeAlert("정답입니다.");$("#qstAnswer"+qstNo).val("Y")}else{$("#answer"+qstNo+"Err").show();makeAlert("아쉽게도 오답입니다.<BR>다시 한번 확인해 주세요.");$("#qstAnswer"+qstNo).val("N")}}else{$("input[name=answer"+qstNo+"]").each(function(idx){var id=$(this).attr("id");var answer=
$("#"+id+"Y").val();if($("#"+id).is(":checked")==true){if(answer=="Y")answerCnt++}else if(answer!="Y")answerCnt++;rplCnt++});if(rplCnt==answerCnt){$("#answer"+qstNo+"Err").hide();makeAlert("정답입니다.");$("#qstAnswer"+qstNo).val("Y")}else{$("#answer"+qstNo+"Err").show();makeAlert("아쉽게도 오답입니다.<BR>다시 한번 확인해 주세요.");$("#qstAnswer"+qstNo).val("N")}}}
function fnPostLayerPop(){var options={oncomplete:function(data){var extraAddr="";if(data.userSelectedType==="R"){if(data.bname!==""&&/[동|로|가]$/g.test(data.bname))extraAddr+=data.bname;if(data.buildingName!==""&&data.apartment==="Y")extraAddr+=extraAddr!==""?", "+data.buildingName:data.buildingName;if(extraAddr!=="")extraAddr=" ("+extraAddr+")"}data.jibunAddress+=extraAddr;data.roadAddress+=extraAddr;fnLoadAddrInfo(data)},width:"100%",height:"100%",maxSuggestItems:5};layerPost.open(options)}
function fnLoadAddrInfo(addrInfo){var html="";var addr="";if(addrInfo.userSelectedType==="R"){html="<p>[도로명]</p>";html+="<p>"+addrInfo.roadAddress+"</p>";addr+="[도로명] "+addrInfo.roadAddress}else{html="<p>[지번명]</p>";html+="<p>"+addrInfo.jibunAddress+"</p>";addr+="[지번명] "+addrInfo.jibunAddress}$("#inpEnterZonecode").val(addrInfo.zonecode);$("#inpEnterAddress").val(addr);$("#inpEnterAddressDiv").empty().append(html);$("#inpEnterAddressDetail").select()}
function fnEmailCheck(email){var exptext=/^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-Za-z0-9\-]+/;if(exptext.test(email)==false)return false;return true}function fnMobileCheck(phoneNum){var regExp=/(01[016789])([1-9]{1}[0-9]{2,3})([0-9]{4})$/;if(regExp.test(phoneNum))return true;else return false}function fnUrlCheck(url){var regExp=/^(http|https):\/\/[^ "]+$/;if(regExp.test(url))return true;else return false}
function fnOnLimitInputVal(selector){var adrsNm=$(selector).val();adrsNm=adrsNm.replace(/[^a-zA-Zㄱ-힣\u119E\u11A20-9\s]/g,"").replace(/\s+/g," ");var totalByte=0;var macLen=50;var len;for(var i=0;i<adrsNm.length;i++){var oneChar=escape(adrsNm.charAt(i));if(oneChar.length==1)totalByte++;else if(oneChar.indexOf("%u")!=-1)totalByte+=2;else if(oneChar.indexOf("%")!=-1)totalByte++;if(totalByte<=macLen)len=i+1}$(selector).val(adrsNm.substring(0,len))}
function fnOnLimitInputValAtDtlAddr(selector){var dtlAddr=$(selector).val();dtlAddr=dtlAddr.replace(/[^a-zA-Zㄱ-힣\u119E\u11A20-9,-/\s]/g,"").replace(/\s+/g," ");$(selector).val(dtlAddr)}function makeAlert(contentsParam,calback){var contentsparam=contentsParam;var alertData={content:contentsparam,btnText:"확인",callback:calback};commonAlert(alertData);openLayer("commonAlert")}function eventPopClose(){$(".evt-pop-close").trigger("click")}
function fnGoLoginPage(){window.location.href=stPath+"member/indexLogin/?returnUrl="+returnUrl;$(".evt-pop-close").trigger("click")}var currentFileSize=0;var currentFileExe="";
var fileUpload={data:{fldNo:""},file:function(callBack,fldNo){fileUpload.callBack=callBack;fileUpload.fileForm("file","");fileUpload.data.fldNo=fldNo},fileFilter:function(callback,filter){fileUpload.callBack=callback;fileUpload.fileForm("file",filter)},image:function(callback){fileUpload.callBack=callback;fileUpload.fileForm("image","")},certificate:function(callback){fileUpload.callBack=callback;fileUpload.fileForm("certificate","")},fileForm:function(type,filter){var html=[];$("#fileUploadForm").remove();
html.push('<form name="fileUploadForm" id="fileUploadForm" method="post" enctype="multipart/form-data">');html.push('\t<div style="display:none;">');html.push('\t\t<input type="file" name="eventUploadFile" id="eventUploadFile" />');html.push('\t\t<input type="hidden" name="uploadType" value="'+type+'">');html.push('\t\t<input type="hidden" name="filter" value="'+filter+'">');html.push("\t</div>");html.push("</form>");$("body").append(html.join(""));$("#eventUploadFile").click()},callBack:null,objId:null,
afterFileSelect:function(file,exCode){$("#phyPath").val(file.filePath);var html="";var maxSize=10;currentFileSize=file.fileSize;currentFileExe=file.fileExe.toUpperCase();var chkFileExe=false;var alertData1={title:"",content:"",callback:"",btnText:"확인"};if(currentFileExe!="JPG"&&currentFileExe!="PNG"){alertData1.content="JPG, PNG 파일만 첨부 가능합니다.";chkFileExe=true}if(chkFileExe){commonAlert(alertData1);openLayer("commonAlert");$("#addField"+fileUpload.data.fldNo).val("");$("input[name$='"+fileUpload.data.fldNo+
"']").val("");return}if(currentFileSize>maxSize*1024*1024){var alertData2={title:"",content:"이미지는 최대 10MB까지 첨부 가능합니다.",callback:"",btnText:"확인"};commonAlert(alertData2);openLayer("commonAlert");return}if($(".file-list"+fileUpload.data.fldNo).children("li").length>=1){var alertData3={title:"",content:"파일은 1개만 첨부 가능합니다.",callback:"",btnText:"확인"};commonAlert(alertData3);openLayer("commonAlert");return}html+="<li>";html+="\t<span>"+file.fileName+"</span>";html+='\t<button type="button" class="ico-del-s" onclick="fileRemove(\''+
fileUpload.data.fldNo+"')\">";html+='\t\t<span class="blind">첨부파일 삭제</span>';html+="\t</button>";html+="</li>";$(".file-list"+fileUpload.data.fldNo).append(html)}};
function fnFileUploadCallBack(result,exCode){var rsltFldNo=fileUpload.data.fldNo;$("#addField"+rsltFldNo).val(result.fileName);$("#fileExe"+rsltFldNo).val(result.fileExe);$("#fileName"+rsltFldNo).val(result.fileName);$("#filePath"+rsltFldNo).val(result.filePath);$("#fileSize"+rsltFldNo).val(result.fileSize);$("#fileType"+rsltFldNo).val(result.fileType);fileUpload.afterFileSelect(result,exCode)}
function fileRemove(fldNo){$(".file-list"+fldNo).children("li").eq(0).remove();$("#addField"+fldNo).val("")}
$(document).on("change","#eventUploadFile",function(){waiting.start();$("#fileUploadForm").ajaxSubmit({url:stPath+"xhr/common/fileUploadResult.do",dataType:"json",success:function(result){waiting.stop();$("#fileUploadForm").remove();if(result.exCode==null||result.exCode==="")if(fileUpload.callBack===undefined||fileUpload.callBack==null)fnFileUploadCallBack(result.file,result.exCode);else fileUpload.callBack(result.file,result.exCode);else makeAlert(result.exMsg)},error:function(xhr,status,error){waiting.stop();
if(xhr.status===1E3)makeAlert("세션이 종료되었습니다.");else makeAlert("오류가 발생되었습니다.<BR>관리자에게 문의하십시요.["+xhr.status+"]["+error+"]")}})});function fnSearchFile(fldNo){fileUpload.file(fnFileUploadCallBack,fldNo)}$(document).on("click",".chkAns",function(){var qstNo=$(this).attr("arg1");var qstTpCd=$(this).attr("arg2");checkAnswer(qstNo,qstTpCd)});$(document).on("click","#inpEnterZonecode, #zoneCodeBtn",function(){fnPostLayerPop()});$(document).on("click","#eventSaveBtn, #reservationBtn",function(){fnSaveEventEntry()});
$(document).on("click","#chk-enter-all",function(){var allChked=$(this).prop("checked");$(".inp-terms").each(function(){$(this).prop("checked",allChked)})});$(document).on("keyup keydown","#inpEnterName",function(){fnOnLimitInputVal($(this))});$(document).on("keyup keydown","#inpEnterAddressDetail",function(){fnOnLimitInputValAtDtlAddr($(this))});var content;$(document).on("keyup","#inpEnterSns",function(){content=$(this).val();$(".sns-count").html("<em class='strong'>"+content.length+"</em> / 500자")});
var content2;$(document).on("input","#inpEnterSerialNum",function(){content2=$(this).val();$(".serial-count").html("<em class='strong'>"+content2.length+"</em> / 500자")});$(document).on("click","#chkSerialNoBtn",fnCheckSerialNo);$(document).on("keyup","input:text[numberOnly]",function(){$(this).val($(this).val().replace(/[^0-9]/g,""))});
$(document).on("click","#microSiteDetailView",function(){var microSiteShopNo=$("input[name=radio-store]:checked").data("shop-no");var microSiteUrl=stPath+"digitalplaza/storeDetail/"+microSiteShopNo;window.open(microSiteUrl);$("#microSiteUrl").val(microSiteUrl)});
$(document).on("click",".btn-tooltop02",function(){var target=$(this).data("tooltip");var goodsVal=$("input[name='chk-goods']:checked").val();var imgUrl="";$(".serialno-usetip").css("z-index",1E3);$.each(goodsSerialInfos,function(idx,val){var goodsId=val.goodsId;if(goodsId==goodsVal)imgUrl="//"+val.serialImgPath});if(imgUrl!=""){$("#serialImg").attr("src",imgUrl);tooltipCenterTop(this,target,380)}});
function fnSaveEventEntry(){$("#focusTarget").val("");if(fnValidationCheck()){if($("#inpEnterSns").val()){var snsUrl=$("#inpEnterSns").val();snsUrl=snsUrl.trim().replace(/^(http|https):\/\//,"");$("#inpEnterSns").val(snsUrl)}$("#addFieldArea").children(".inp-box").each(function(){var $addFieldId=$(this).find("[id^='addField']");var fldtpcd=$addFieldId.data("fldtpcd");if(fldtpcd===10||fldtpcd===20||fldtpcd===90){var fldVal=$addFieldId.val();fldVal=fldVal.trim().replace(/^(http|https):\/\//,"");$addFieldId.val(fldVal)}});
createJsonStr();var options={url:stPath+"xhr/event/insertEventEntry",data:$("#eventEntryPopFrm").serialize(),done:function(data){var result=data.result;makeAlert(result.resultMsg,eventPopClose)}};$(".btn-box").removeAttr("style");if(isPreView)return;oneTimeChk=false;ajax.call(options)}else{var id=$("#focusTarget").val();var type=$("#focusTargetType").val();if(type=="")setTimeout(function(){$("#"+id).focus()},1);else $("input[name="+id+"]").focus();return}}
function fnValidationCheck(){var passyn="Y";$(".error-msg").hide();if(membershipNo==""||membershipNo==null)$("#inpCounselMembershipErr").show();var collectItem={10:{id:"inpEnterName",errId1:"inpEnterNameErr",errId2:"inpEnterNameErr",callback:null},20:{id:"inpEnterCall",errId1:"inpEnterCallErr",errId2:"inpEnterCallErr2",callback:fnMobileCheck},30:{id:"inpEnterEmail",errId1:"inpEnterEmailErr",errId2:"inpEnterEmailErr2",callback:fnEmailCheck},40:{id:"inpEnterZonecode",errId1:"inpEnterZonecodeErr",errId2:"inpEnterZonecodeErr",
callback:null},50:{id:"inpEnterSns",errId1:"inpEnterSnsErr",errId2:"inpEnterSnsErr2",callback:fnUrlCheck},60:{id:"inpCounselMembership",errId1:"inpCounselMembershipErr",errId2:"inpCounselMembershipErr",callback:null}};$.each(collectItems,function(idx,val){var collectItemId=collectItem[val.collectItemCd].id;var collectItemErrId=collectItem[val.collectItemCd].errId1;var collectItemVal=$("#"+collectItemId).val();if(collectItemVal==""){$("#"+collectItemErrId).show();passyn="N";fnFocusIdSet(collectItemId)}});
var validationSubResult;var chkArr=["20","30","50"];$.each(chkArr,function(i,val){validationSubResult=fnValidationSub(collectItem[val]);if(!validationSubResult){passyn="N";fnFocusIdSet(collectItem[val].id)}});passyn=fnValidationAddFieldsChk(passyn);if(eventGbCd=="40")$("#eventNm").val(entryEvent.ttl);if(eventGbCd=="50")passyn=fnValidationChk50(passyn);if(eventGbCd=="60")passyn=fnValidationChk60(passyn);if(eventGbCd=="80"){$("#visPlazaNo").val($("input[name=radio-store]:checked").val());$("#visShopNo").val($("input[name=radio-store]:checked").data("shop-no"));
$("#visPlazaNm").val($("input[name=radio-store]:checked").next().text());$("#visHopeDt").val($("#visitDate").val());$("#eventNm").val(entryEvent.ttl);var seletedPlazaNo=$("input[name=radio-store]:checked").val();if(seletedPlazaNo==undefined){passyn="N";$("#radio-store1Err").show();fnFocusIdSet("radio-store1")}}passyn=fnValidationPrivacyPolicy(passyn);return passyn=="Y"?true:false}
function fnValidationSub(obj){var value=$("#"+obj.id).val();if(value!=""){var chkFlag=obj.callback(value);if(!chkFlag){$("#"+obj.errId2).show();return false}}return true}function fnValidationChk50(passyn){var goodsVal=$("input[name=chk-goods]:checked").val();if(goodsVal==undefined||goodsVal==""){$("#chk-goods-err").show();passyn="N";fnFocusIdSet("chk-goods","name")}if($("#serialNumChk").val()=="N"){$("#inpEnterSerialNumErr").show();passyn="N";fnFocusIdSet("inpEnterSerialNum")}return passyn}
function fnValidationChk60(passyn){var failCnt=0;var focusId;var tpCd;var ulClassNm;$("input[name=qstAnswer]").each(function(){ulClassNm=$(this).attr("id");var errMsgIdCd=ulClassNm.replaceAll("qstAnswer","");if($(this).val()=="N"){failCnt++;if(failCnt==1){tpCd=$(this).data("qsttpcd");if(tpCd=="30")fnFocusIdSet("answer"+errMsgIdCd);else{focusId=$("."+ulClassNm+" > li").children(":eq(0)").attr("id");fnFocusIdSet(focusId)}}$("#answer"+errMsgIdCd+"Err").show()}});if(failCnt>0)passyn="N";return passyn}
function fnValidationPrivacyPolicy(passyn){var plcyAltYn=entryEvent.plcyAltYn;var isRqidChkPlcy=false;$("#privacyPolicy .entryAgreeY").each(function(idx,item){var id=$(item).attr("id");if($("#"+id).is(":checked")==false){$("#err-"+id).show();passyn="N";fnFocusIdSet(id)}});if(passyn!="N"){var $optPolicy=$("#privacyPolicy .inp-terms").not(".entryAgreeY");if($optPolicy.length!=0)$optPolicy.each(function(){if($(this).is(":checked")==false){isRqidChkPlcy=true;return false}else{isRqidChkPlcy=false;return true}})}if(plcyAltYn==
"Y")if(passyn=="Y")if(!oneTimeChk&&isRqidChkPlcy){var alertData={title:"",content:"광고성 정보 수신에 동의하지 않은 경우<br>이벤트 관련 정보, 혜택 안내를 받으실 수 없습니다.<br>[광고성 정보 수신] 동의 여부를 확인해주세요.",callback:"",btnText:"확인"};commonAlert(alertData);openLayer("commonAlert");passyn="N";oneTimeChk=true}else if(oneTimeChk&&!isRqidChkPlcy)passyn="Y";return passyn}
function fnValidationAddFieldsChk(passyn){$.each(addFields,function(idx,item){var id="addField"+item.fldNo;var fldTpCd=item.fldTpCd;var errorMsgId="#"+id+"Err";var fldValOptYn=item.fldValOptYn==null||item.fldValOptYn===undefined?"N":item.fldValOptYn;var fldTpCdArr_10_20_60_90=["10","20","60","90"];if(fldValOptYn=="N")if(fldTpCdArr_10_20_60_90.indexOf(fldTpCd)>-1){if($("#"+id).val()==""){$(errorMsgId).show();passyn="N";fnFocusIdSet(id)}}else if(fldTpCd=="30"){var inputValue=$("input[name='"+id+"']:checked").val();
if(inputValue==undefined||inputValue==""){$(errorMsgId).show();passyn="N";fnFocusIdSet(id,"name")}}else if(fldTpCd=="40"){var chkCnt=0;$("input[name='"+id+"']:checked").each(function(){if($(this).val()!="")chkCnt++});if(chkCnt==0){$(errorMsgId).show();passyn="N";fnFocusIdSet(id,"name")}}else if(fldTpCd=="50"){var selText=$("#"+id+" li.focused").text();if(selText==""){$(errorMsgId).show();passyn="N";fnFocusIdSet(id+"Btn")}}});return passyn}
function fnFocusIdSet(targetId,type){if($("#focusTarget").val()==""){$("#focusTarget").val(targetId);if(type!="")$("#focusTargetType").val(type)}}
function createJsonStr(){var jsonStr=new Object;var rowArr=new Array;var index=0;$.each(addFields,function(idx,item){var jobj=new Object;var id="addField"+item.fldNo;var fldTpCd=item.fldTpCd;if(fldTpCd=="10"||fldTpCd=="20"||fldTpCd=="90"){var inputValue126=$("#"+id).val();if(inputValue126!=""){jobj.fldNo=item.fldNo+"";jobj.fldGrp=item.fldGrp;jobj.fldTpCd=item.fldTpCd+"";jobj.fldNm=item.fldNm;jobj.fldVal=inputValue126;rowArr.push(jobj);jsonStr.addFieldList=rowArr}index++}else if(fldTpCd=="30"){var inputValue3=
$("input[name='"+id+"']:checked").val();if(inputValue3!=undefined&&inputValue3!=""){jobj.fldNo=item.fldNo+"";jobj.fldGrp=item.fldGrp;jobj.fldTpCd=item.fldTpCd+"";jobj.fldNm=item.fldNm;jobj.fldVal=inputValue3;rowArr.push(jobj);jsonStr.addFieldList=rowArr}index++}else if(fldTpCd=="40"){$("input[name='"+id+"']:checked").each(function(a,b){var obj2=new Object;obj2.fldNo=item.fldNo+"";obj2.fldGrp=item.fldGrp;obj2.fldTpCd=item.fldTpCd+"";obj2.fldNm=item.fldNm;obj2.fldVal=$(this).val();rowArr.push(obj2);
jsonStr.addFieldList=rowArr});index++}else if(fldTpCd=="50"){var selText=$("#"+id+" li.focused").text();if(selText!=""){jobj.fldNo=item.fldNo+"";jobj.fldGrp=item.fldGrp;jobj.fldTpCd=item.fldTpCd+"";jobj.fldNm=item.fldNm;jobj.fldVal=selText;rowArr.push(jobj);jsonStr.addFieldList=rowArr}index++}else if(fldTpCd=="60"){var inputValue126=$("#"+id).val();var filePath=$("#filePath"+item.fldNo).val();if(inputValue126!="")if(item.fldVal!=""&&item.fldVal!=null&&item.fldVal!=undefined){var fldValMeta=item.fldVal.split(",");
if(fldValMeta.length==1){jobj.fldNo=item.fldNo+"";jobj.fldGrp=item.fldGrp;jobj.fldTpCd=item.fldTpCd+"";jobj.fldNm=item.fldNm;jobj.fldVal=inputValue126+";"+filePath;jobj.fldValMeta=fldValMeta[0];rowArr.push(jobj);jsonStr.addFieldList=rowArr}else if(fldValMeta.length==2){jobj.fldNo=item.fldNo+"";jobj.fldGrp=item.fldGrp;jobj.fldTpCd=item.fldTpCd+"";jobj.fldNm=item.fldNm;jobj.fldVal=inputValue126+";"+filePath;jobj.fldValMeta=fldValMeta[0];rowArr.push(jobj);jsonStr.addFieldList=rowArr;if($("#eventAddYn").val()==
"N"){var jobj2=new Object;jobj2.fldNo=item.fldNo+1+"";jobj2.fldGrp=item.fldGrp;jobj2.fldTpCd=item.fldTpCd+"";jobj2.fldNm=item.fldNm;jobj2.fldVal=inputValue126+";"+filePath;jobj.fldValMeta=fldValMeta[1];rowArr.push(jobj2);jsonStr.addFieldList=rowArr}}}index++}});var rowArrPlcy=new Array;$(".plcyGbCd20").prop("checked",true);$("input[data-chkgrp-name=checkEventEnter]").each(function(idx,item){var plcyObj=new Object;var id=$(item).attr("id");plcyObj.policyNo=$("#"+id).data("policyno")+"";plcyObj.fldGrp=
idx;if($("#"+id).is(":checked")==true)plcyObj.seletedYn="Y";else plcyObj.seletedYn="N";rowArrPlcy.push(plcyObj);jsonStr.plcyAgreeList=rowArrPlcy;index++});var biztalkUseYn=$("#biztalkUseYn").val();if(biztalkUseYn=="Y"){var mktRcvSelYnLen=$("input[data-chkgrp-name=checkEventEnter].plcyGbCd30").length;var plcyGbCd30idx=0;$("input[data-chkgrp-name=checkEventEnter].plcyGbCd30").each(function(idx,item){var id=$(item).attr("id");if($("#"+id).is(":checked")==true)plcyGbCd30idx++});if(mktRcvSelYnLen==plcyGbCd30idx)$("#mktRcvSelYn").val("Y");
else $("#mktRcvSelYn").val("N")}if(index==0)$("#jsonStr").val("noData");else $("#jsonStr").val(JSON.stringify(jsonStr))}
function drawTooltipHtmlCode(){var html="";html+='<div class="tooltip-layer serialno-usetip" tabindex="0">';html+='    <div class="tooltip-title"><h2>시리얼번호 확인</h2></div>';html+='    <div class="tooltip-content">';html+='        <div class="serial-img">';html+='            <img src="" alt="" id="serialImg">';html+="        </div>";html+="    </div>";html+='    <button type="button" class="btn-tooltip-close"><em class="blind">닫기</em></button>';html+="</div>\t";return html}
function drawPopHtmlCode(){var html="";html+='<form id="eventEntryPopFrm">';html+='\t<input type="hidden" id="serialNumChk" value="N"/>';html+='\t<input type="hidden" id="serialNum" name="serialNum" value=""/>';html+='\t<input type="hidden" id="mdlCode" name="mdlCode" value=""/>';html+='\t<input type="hidden" id="focusTarget" value=""/>';html+='\t<input type="hidden" id="focusTargetType" value=""/>';html+='\t<input type="hidden" id="jsonStr" name="jsonStr" value=""/>';html+='\t<input type="hidden" id="entryEventNo" name="eventNo" value=""/>';
html+='\t<input type="hidden" id="evtGbCd" name="evtGbCd" value=""/>';html+='\t<input type="hidden" id="prtcpPsbGbCd" name="prtcpPsbGbCd" value=""/>';html+='\t<input type="hidden" id="prtcpPsbCnt" name="prtcpPsbCnt" value=""/>';html+='\t<input type="hidden" id="visPlazaNo" name="visPlazaNo" value=""/>';html+='\t<input type="hidden" id="visShopNo" name="visShopNo" value=""/>';html+='\t<input type="hidden" id="visPlazaNm" name="visPlazaNm" value=""/>';html+='\t<input type="hidden" id="visHopeDt" name="visHopeDt" value=""/>';
html+='\t<input type="hidden" id="visPlazaTel" name="visPlazaTel" value=""/>';html+='\t<input type="hidden" id="visPlazaAddr" name="visPlazaAddr" value=""/>';html+='\t<input type="hidden" id="cpNo" name="cpNo" value=""/>';html+='\t<input type="hidden" id="eventNm" name="eventNm" value=""/>';html+='\t<input type="hidden" id="microSiteUrl" name="microSiteUrl" value=""/>';html+='\t<input type="hidden" id="biztalkTmplTxt" name="biztalkTmplTxt" value=""/>';html+='\t<input type="hidden" id="biztalkUseYn" name="biztalkUseYn" value=""/>';
html+='\t<input type="hidden" id="mktRcvSelYn" name="mktRcvSelYn" value=""/>';html+='\t<input type="hidden" id="weekdayCloseTime" name="weekdayCloseTime" value=""/>';html+='\t<input type="hidden" id="weekdayOpenTime" name="weekdayOpenTime" value=""/>';html+='\t<input type="hidden" id="weekendCloseTime" name="weekendCloseTime" value=""/>';html+='\t<input type="hidden" id="weekendOpenTime" name="weekendOpenTime" value=""/>';html+='\t<input type="hidden" id="eventAddYn" name="eventAddYn" value=""/>';
html+='\t<div class="layer-pop layer-normal layer-event-exhibition" id="popupExhibitionEnter" tabindex="0" data-popup-layer="popupExhibitionEnter" data-focus="popupExhibitionEnter">';html+='       <button type="button" id="exhibition" data-popup-target="popupExhibitionEnter" style="display: none;"></button>';html+='\t    <div class="layer-header" id="evtHeader">';html+="\t        <h2>응모 하기</h2>";html+="\t    </div>";html+='\t    <div class="layer-content">';html+='\t        <div class="frm-login ">';
html+='\t            <form action="">';html+='\t                <fieldset class="secureInp">';html+="\t                    <legend>응모 입력 폼</legend>";html+='\t\t\t\t\t\t <div class="event-img">';html+='\t                        <img src="" alt="" id="evtImg">';html+="\t                    </div>";html+='\t                    <div class="vote-txt-box eventGbCd70">';html+='\t                        <p><strong><span id="evtNm"></span></strong> 투표에 참여해주셔서 감사합니다.</p>';html+="\t                        <p>투표 이벤트 추첨을 위해 아래 정보를 작성해주세요.</p>";
html+='\t                        <p class="txt-major">* 투표하기는 1회만 가능합니다.</p>';html+="\t                    </div>";html+='\t                    <div class="user-info-box secure-pop-form user-form">';html+='\t                        <div class="secure-pop-tit bottom-line"><span class="titleNo">01. </span><span id="popTitle">응모자 정보</span></div>';html+='\t                        <div class="secure-pop form-write">';html+='\t                            <div class="inp-box entryCollect10 entryCollect">';
html+='\t                                <label for="inpEnterName" class="lb-line">이름</label>';html+="\t\t                            <div>";html+='\t\t                                <input type="text" id="inpEnterName" name="inpEnterName" class="inp-line" value="" readonly="readonly">';html+='\t\t                                <div class="error-msg" id="inpEnterNameErr">';html+="\t                                    \t<p>이름을 입력해 주세요.</p>";html+="\t                                    </div>";html+=
"\t\t                            </div>";html+="\t                            </div>";html+='\t                            <div class="inp-box entryCollect20 entryCollect">';html+='\t                                <label for="inpEnterCall" class="lb-line">연락처</label>';html+="\t\t                            <div>";html+='\t                                    <input type="text" id="inpEnterCall" name="inpEnterCall" class="inp-line" placeholder="(-) 없이 숫자만 입력해 주세요." numberOnly maxlength="11">';html+=
'\t                                    <div class="error-msg" id="inpEnterCallErr">';html+="\t                                    \t<p>연락처를 입력해 주세요.</p>";html+="\t                                    </div>";html+='\t                                    <div class="error-msg"  id="inpEnterCallErr2">';html+="\t                                    \t<p>연락처가 올바르지 않습니다.</p>";html+="\t                                    </div>";html+="\t\t                            </div>";html+="\t                            </div>";
html+='\t\t\t\t\t\t\t\t<div class="inp-box entryCollect60 entryCollect">';html+='\t\t\t\t\t\t\t\t    <label for="inpCounselMembership" class="lb-line line-double">삼성전자 <br>멤버십 번호</label>';html+="\t\t\t\t\t\t\t\t    <div>";html+='\t\t\t\t\t\t\t\t        <input type="text" id="inpCounselMembership" class="inp-line" value="" readonly="readonly">';html+='\t                                    <div class="error-msg" id="inpCounselMembershipErr">';html+="\t                                    </div>";html+=
"\t\t\t\t\t\t\t\t    </div>";html+="\t\t\t\t\t\t\t\t</div>";html+='\t                            <div class="inp-box entryCollect30 entryCollect">';html+='\t                                <label for="inpEnterEmail" class="lb-line">이메일</label>';html+="\t\t                            <div>";html+='\t                                    <input type="text" id="inpEnterEmail" name="inpEnterEmail" class="inp-line" placeholder="이메일을 입력해 주세요.">';html+='\t                                    <div class="error-msg" id="inpEnterEmailErr">';
html+="\t                                        <p>이메일을 입력해 주세요. </p>";html+="\t                                    </div>";html+='\t                                    <div class="error-msg" id="inpEnterEmailErr2">';html+="\t                                        <p>이메일을 정확히 입력해 주세요. </p>";html+="\t                                    </div>";html+="\t\t                            </div>";html+="\t                            </div>";html+='\t                            <div class="inp-box entryCollect40 entryCollect">';
html+='\t                                <label for="inpEnterZonecode" class="lb-line">주소</label>';html+='\t\t                            <div class="address-box">';html+='\t\t                                <div class="address-search">';html+='\t                                        <input type="text" id="inpEnterZonecode" name="inpEnterZonecode"readonly="readonly" class="inp-line" title="우편번호" placeholder="우편번호를 검색해 주세요." value="">';html+='\t                                        <button type="button" class="btn btn-s btn-type1" id="zoneCodeBtn">우편번호</button>';
html+="\t                                    </div>";html+='\t                                    <div class="address-txt">';html+='\t                                        <div id="inpEnterAddressDiv" >';html+="\t                                        </div>";html+='\t                                        \t<input type="hidden" id="inpEnterAddress" name="inpEnterAddress">';html+="\t                                    </div>";html+='\t                                    <div class="address-detail">';
html+='\t                                        <input type="text" name="inpEnterAddressDetail" id="inpEnterAddressDetail" class="inp-line" placeholder="상세주소를 입력해 주세요.">';html+="\t                                    </div>";html+='\t                                     <div class="error-msg" id="inpEnterZonecodeErr">';html+="\t                                        <p>우편번호를 통해 주소를 선택해 주세요.</p>";html+="\t                                    </div>";html+="\t\t                            </div>";html+=
"\t                            </div>";html+='\t                            <div class="inp-box entryCollect50 entryCollect">';html+='\t                                <label for="inpEnterSns" class="lb-line">SNS 게시물 URL</label>';html+="\t\t                            <div>";html+='\t\t                                <div class="inquiry-con">';html+='\t\t                                    <textarea id="inpEnterSns" name="inpEnterSns" class="inp-line pop-tArea" placeholder="게시한 SNS URL을 입력해 주세요." maxlength="500"></textarea>';
html+='\t\t                                    <span class="txt-count sns-count"><em class="strong">0</em> / 500자</span>';html+="\t\t                                </div>";html+='\t                                    <div class="error-msg" id="inpEnterSnsErr">';html+="\t                                       <p>SNS 게시물 URL을 입력해 주세요.</p>";html+="\t                                    </div>";html+='\t                                    <div class="error-msg" id="inpEnterSnsErr2">';html+="\t                                       <p>URL을 정확하게 입력해 주세요.</p>";
html+="\t                                    </div>";html+="\t                                </div>";html+="\t                            </div>";html+='\t                            <p class="txt-general eventGbCd70">* 잘못된 정보 입력 시 투표에 제한이 있을 수 있으며, 경품 당첨이 취소됩니다.</p>';html+='\t                            <div id="addFieldArea"> ';html+="\t                            </div>";html+='\t                            <div class="inp-box goodsSelect eventGbCd50">';html+='\t                                <label for="chk-goods-1" class="lb-line lb-top">제품 선택</label>';
html+="\t\t                            <div>";html+='\t                                    <ul class="chk-list-box chk-form mo-col1" id="goodsUl"></ul>';html+='\t                                     <div class="error-msg" id="chk-goods-err">';html+="\t                                        <p>제품을 선택해 주세요.</p>";html+="\t                                    </div>";html+="\t\t                            </div>";html+="\t                            </div>";html+='\t                            <div class="inp-box goodsSelect eventGbCd50">';
html+='\t                                <p class="label-box">';html+='\t                                    <label for="inpEnterSerialNum" class="lb-line">제품 시리얼 <br>넘버</label>';html+='\t                                    <i class="btn-tooltop02" data-tooltip="serialno-usetip"><span>툴팁보기(레이어열림)</span></i>';html+="\t                                </p>";html+="\t\t                            <div>";html+='\t\t                                <div class="inquiry-con">';html+='\t\t                                    <textarea id="inpEnterSerialNum" name="inpEnterSerialNum" class="inp-line pop-tArea" placeholder="제품 시리얼 넘버 확인 후 입력해 주세요." maxlength="500"></textarea>';
html+='\t\t                                    <span class="txt-count serial-count"><em class="strong">0</em> / 500자</span>';html+="\t                                    </div>";html+='\t                                    <div class="serial-box">';html+='\t                                        <p class="essential">* 제품의 시리얼 넘버를 입력하신 후 [확인하기] 버튼을 눌러주세요.</p>';html+='\t                                        <button type="button" class="btn btn-s btn-type1" id="chkSerialNoBtn">확인하기</button>';html+=
"\t                                    </div>";html+='\t                                     <div class="error-msg" id="inpEnterSerialNumErr">';html+="\t                                        <p>시리얼 넘버를 입력 후 확인해 주세요.</p>";html+="\t                                    </div>";html+="\t\t                            </div>";html+="\t                            </div>";html+="\t                        </div>";html+="\t                    </div>";html+='\t                    <div class="survey-box qstList eventGbCd60">';
html+="\t                    </div>";html+='\t\t\t\t\t\t<div class="user-info-box secure-pop-form user-form eventGbCd80">';html+='\t\t\t\t\t\t\t<div class="secure-pop-tit bottom-line"><span class="titleNo">02. </span>매장선택</div>';html+='\t\t\t\t\t\t    <p class="txt-general">매장 상담 가능한 매장 및 매장상담 희망일을 선택하세요.</p>';html+='\t\t\t\t\t\t    <div class="secure-pop">';html+='\t\t\t\t\t\t        <div class="inp-box">';html+='\t\t\t\t\t\t            <label for="inpCounselName" class="lb-line">시/도 선택</label>';
html+="\t\t\t\t\t\t            <div>";html+="\t\t\t\t\t\t                <div>";html+='\t\t\t\t\t\t                    <div class="select-box">';html+='\t\t\t\t\t\t                        <div id="dropAge" class="wrap-droplist">';html+='\t\t\t\t\t\t                            <button class="droplist-button selected" aria-haspopup="listbox" aria-labelledby="dropAreaBtn" id="dropAreaBtn">서울</button>';html+='\t\t\t\t\t\t                            <ul class="droplist" id="dropSiDo" tabindex="-1" role="listbox" aria-labelledby="dropAreaBtn" aria-activedescendant="dropArea1-1">';
html+="\t\t\t\t\t\t                            </ul>";html+="\t\t\t\t\t\t                        </div>";html+="\t\t\t\t\t\t                    </div>";html+="\t\t\t\t\t\t                </div>";html+="\t\t\t\t\t\t            </div>";html+="\t\t\t\t\t\t        </div>";html+='\t\t\t\t\t\t        <div class="inp-box">';html+='\t\t\t\t\t\t            <label for="inpCounselCall" class="lb-line">시/군/구 선택</label>';html+="\t\t\t\t\t\t           <div>";html+='\t\t\t\t\t\t                <div class="select-box">';
html+='\t\t\t\t\t\t                    <div id="dropAge" class="wrap-droplist">';html+='\t\t\t\t\t\t                        <button class="droplist-button selected" aria-haspopup="listbox" aria-labelledby="dropAreaBtn2" id="dropAreaBtn2">강남구</button>';html+='\t\t\t\t\t\t                        <ul class="droplist" id="dropSiGunGu" tabindex="-1" role="listbox" aria-labelledby="dropAreaBtn2" aria-activedescendant="dropArea2-1">';html+="\t\t\t\t\t\t                        </ul>";html+="\t\t\t\t\t\t                    </div>";
html+="\t\t\t\t\t\t                </div>";html+="\t\t\t\t\t\t            </div>";html+="\t\t\t\t\t\t        </div>";html+='\t\t\t\t\t\t        <ul class="chk-form style-btn store-select-list">';html+="\t\t\t\t\t\t        </ul>";html+='\t\t\t\t\t\t\t\t<div class="error-msg" id="radio-store1Err" style="text-align: center;">';html+="\t\t\t\t\t\t\t\t    <p>매장을 선택하세요</p>";html+="\t\t\t\t\t\t\t\t</div>";html+='\t\t\t\t\t\t        <div class="store-detail-info">';html+='\t\t\t\t\t\t            <div class="store-detail">';
html+='\t\t\t\t\t\t                <p class="store-name"></p>';html+="\t\t\t\t\t\t                <dl>";html+="\t\t\t\t\t\t                    <dt>주소</dt>";html+='\t\t\t\t\t\t                    <dd id="storeAddr"></dd>';html+="\t\t\t\t\t\t                </dl>";html+="\t\t\t\t\t\t                <dl>";html+="\t\t\t\t\t\t                    <dt>전화번호</dt>";html+='\t\t\t\t\t\t                    <dd id="storeTel"></dd>';html+="\t\t\t\t\t\t                </dl>";html+="\t\t\t\t\t\t                <dl>";
html+="\t\t\t\t\t\t                    <dt>영업시간</dt>";html+='\t\t\t\t\t\t                    <dd id="storeOpenTime"></dd>';html+="\t\t\t\t\t\t                </dl>";html+="\t\t\t\t\t\t                <dl>";html+="\t\t\t\t\t\t                    <dt>주차공간</dt>";html+='\t\t\t\t\t\t                    <dd id="storeParkingInfo"></dd>';html+="\t\t\t\t\t\t                </dl>";html+='\t\t\t\t\t\t                <p class="btn-more-box"><a href="#" class="link" id="microSiteDetailView">상세보기 ></a></p>';html+=
"\t\t\t\t\t\t            </div>";html+='\t\t\t\t\t\t            <div class="store-detail-mapbox" id="map">';html+="\t\t\t\t\t\t                \x3c!-- 맵 영역 --\x3e";html+="\t\t\t\t\t\t            </div>";html+='\t\t\t\t\t\t            <div class="hope-visit-date">';html+='\t\t\t\t\t\t                <p class="date-title">방문 희망 일자 선택</p>';html+="\t\t\t\t\t\t                <dl>";html+="\t\t\t\t\t\t                    <dt>날짜선택</dt>";html+="\t\t\t\t\t\t                    <dd>";html+='\t\t\t\t\t\t                        <input type="text" id="visitDate" name="visitDate" placeholder="방문 희망 일자를 선택해 주세요." class="inp-line inp-calendar">';
html+='\t\t\t\t\t\t                        <p class="txt">* 디지털프라자 매장 마감시간은 20시 30분입니다.</p>';html+="\t\t\t\t\t\t                    </dd>";html+="\t\t\t\t\t\t                </dl>";html+="\t\t\t\t\t\t            </div>";html+="\t\t\t\t\t\t        </div>";html+="\t\t\t\t\t\t    </div>";html+="\t\t\t\t\t\t</div>";html+='\t                    <div class="user-info-box secure-pop-form terms-form">';html+='\t                        <div class="secure-pop-tit bottom-line">';html+='\t                            <span class="titleNo">03. </span>개인정보 수집·이용 동의 <span class="ico-required">*<span>필수입력</span></span>';
html+="\t                        </div>";html+='\t                        <div class="secure-pop terms-con">';html+='\t                            <p class="txt-general">';html+="\t\t\t                                귀하께서는 본 동의 안내 문구를 숙지하셨으며, 안내문구에 대해 거절하실 수 있습니다.<br>";html+="\t\t\t                                단, 거절하신 경우에는 이벤트 응모가 제한되실 수 있습니다.";html+="\t                            </p>";html+='\t                            <div class="chk-form allChk-box">';html+='\t                                <input id="chk-enter-all" data-allchk-name="allCheck" data-children-name="checkEventEnter" type="checkbox" required="" title=""';
html+='\t                                    class="checkBoxTerms">';html+='\t                                <label for="chk-enter-all" class="chk-all">모든 약관을 확인하고 전체 동의합니다.</label>';html+="\t                            </div>";html+='\t                            <div id="privacyPolicy"></div>';html+="\t                        </div>";html+='\t                        <div class="help-box">';html+="\t                            <p>";html+='\t\t\t                                개인정보 처리에 대한 상세한 사항은 삼성전자 웹사이트  (<a href="http://www.samsung.com/sec" class="link" target="_blank">www.samsung.com/sec</a>)에 공개한 "삼성닷컴 이벤트 개인정보 처리방침"을 참조하십시오.<br>';
html+="\t\t\t                                다만, 본 동의서 내용과 상충되는 부분은 본 동의서 내용을 우선합니다.";html+="\t                            </p>";html+="\t                        </div>";html+="\t                    </div>";html+='\t\t\t\t\t\t<div class="user-info-box secure-pop-form terms-form  eventGbCd80">';html+='\t\t\t\t\t\t    <div class="secure-pop-tit bottom-line">';html+='\t\t\t\t\t\t        <span class="titleNo">04. </span>신청 정보 확인';html+="\t\t\t\t\t\t    </div>";html+='\t\t\t\t\t\t    <p class="txt-general">방문 희망일자와 매장 정보를 확인 후 신청을 완료하세요.</p>';
html+='\t\t\t\t\t\t    <div class="final-check-box">';html+='\t\t\t\t\t\t        <p class="txt1 storeRsltMsg"><span class="txt-major selectedResultMsg"></span>으로<br> 매장방문을 신청합니다.</p>';html+='\t\t\t\t\t\t        <p class="txt2">※ 신청 시 카카오 알림톡으로 &lt;“<span id="ftEvtNm"></span>” 매장상담예약&gt;<br> 초대장이 발송됩니다.</p>';html+='\t\t\t\t\t\t        <p class="btn-area"><button type="button" class="btn btn-d btn-type2" id="reservationBtn">신청하기</button></p>';html+="\t\t\t\t\t\t    </div>";html+="\t\t\t\t\t\t</div>";
html+="\t                </fieldset>";html+="\t            </form>";html+='\t            <div class="btn-box " id="eventBtn_Area_div">';html+='\t\t            <button type="button" class="btn btn-d btn-type2" id="eventSaveBtn">이벤트 응모</button>';html+="\t\t        </div>";html+="\t        </div>";html+="\t    </div>";html+='\t    <button type="button" class="pop-close evt-pop-close" data-focus-next="popupExhibitionEnter">팝업닫기</button>';html+="\t</div>\t";html+="</form>";return html};
