var shareSet=false;var shareUrl="";var shareTitle="";var shareImage="";var shareDesc="";var shareList="";var kakaoAppKey="";function shareInit(kakaoKey,facebookId){kakaoAppKey=kakaoKey;Kakao.init(kakaoAppKey)}function shareInitKakao(kakaoKey){kakaoAppKey=kakaoKey;Kakao.init(kakaoAppKey)}function openSns(url,title,image,desc){shareUrl=url;shareTitle=title;shareImage=image;shareDesc=desc;shareSet=true}if(kakaoAppKey!=""&&kakaoAppKey!=null&&kakaoAppKey!=undefined)Kakao.init(kakaoAppKey);
var snsShare={facebook:function(url){if(url==null||url=="")url=document.location.href;window.open("http://www.facebook.com/sharer.php?u="+encodeURIComponent(url),"facebookSharePopup","resizable=no width=526 height=158")},kakaoTalk:function(url,title,image,desc){if(url==null||url=="")url=document.location.href;var setting={objectType:"feed",content:{title:title,description:desc,imageUrl:image,link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:"자세히 보기",link:{mobileWebUrl:url,webUrl:url}}],installTalk:true,
fail:shareFail};Kakao.Link.sendDefault(setting)},kakaoTalkWithOption:function(data){if(data.url==null||data.url=="")data.url=document.location.href;var setting={objectType:"feed",content:{title:data.title,description:data.desc,imageUrl:data.image,link:{mobileWebUrl:data.url,webUrl:data.url}},buttons:[{title:data.buttonTitle?data.buttonTitle:"자세히 보기",link:{mobileWebUrl:data.url,webUrl:data.url}}],installTalk:true,fail:shareFail};if(data.imgWidth)setting.content.imageWidth=data.imgWidth;if(data.imgHeight)setting.content.imageHeight=
data.imgHeight;Kakao.Link.sendDefault(setting)},kakaoTalkCallback:function(url,title,image,desc,eventNo,mbrNo){if(url==null||url=="")url=document.location.href;var setting={objectType:"feed",content:{title:title,description:desc,imageUrl:image,link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:"자세히 보기",link:{mobileWebUrl:url,webUrl:url}}],serverCallbackArgs:{eventNo:eventNo,mbrNo:mbrNo},installTalk:true,fail:shareFail};Kakao.Link.sendDefault(setting)},kakaoStory:function(url,title,image,desc){if(url==
null||url=="")url=document.location.href;var text=title;if(title!=desc)text+="\n"+desc;Kakao.Story.share({url:url,text:text})},kakaoTalkPresent:function(url,title,templateImage,goodsImg,goodsNm,dDayDate,sndrNm){if(url==null||url=="")url=document.location.href;var setting={objectType:"feed",content:{title:sndrNm+"님께서 보낸 선물이 도착하였습니다.",description:"",imageUrl:templateImage,imageWidth:885,imageHeight:690,link:{mobileWebUrl:url,webUrl:url}},itemContent:{profileText:"",profileImageUrl:goodsImg,titleImageUrl:goodsImg,
titleImageText:goodsNm,titleImageCategory:"수락기한 : "+dDayDate},buttons:[{title:"선물 받으러 가기",link:{mobileWebUrl:url,webUrl:url}}],installTalk:true,fail:shareFail};Kakao.Link.sendDefault(setting)},kakaoTalkBuyMe:function(url,goodsImg,goodsNm,goodsMdl){if(url==null||url=="")url=document.location.href;var setting={objectType:"feed",content:{title:"한번 구경해볼래요? \n제가 정말 갖고 싶은 상품이에요!",description:"",imageUrl:"https://images.samsung.com/kdp/gift/gift-kakao-share.png",imageWidth:800,imageHeight:800,link:{mobileWebUrl:url,
webUrl:url}},itemContent:{titleImageUrl:goodsImg,titleImageText:goodsNm,titleImageCategory:goodsMdl},buttons:[{title:"선물하러 가기",link:{mobileWebUrl:url,webUrl:url}}],installTalk:true,fail:shareFail};Kakao.Link.sendDefault(setting)},kakaoTalkRecommendGooods:function(url){if(url==null||url=="")url=document.location.href;var setting={objectType:"feed",content:{title:"추천 받으신 삼성 제품 지금 확인해보세요!",description:"",imageUrl:"https://images.samsung.com/kdp/_pub/recommend/recommend-img.jpg",imageWidth:800,imageHeight:800,
link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:"내게 맞는 삼성 제품 확인하기",link:{mobileWebUrl:url,webUrl:url}}],installTalk:true,fail:shareFail};Kakao.Link.sendDefault(setting)}};
function share(type){if(!shareSet){shareUrl=$(location).attr("href");shareTitle=$("meta[name='title']").attr("content");shareImage=$("meta[property='og:image']").attr("content");shareDesc=$("meta[name='description']").attr("content")}if(type=="facebook")snsShare.facebook(shareUrl);else if(type=="kakaostory")snsShare.kakaoStory(shareUrl,shareTitle,shareImage,shareDesc);else if(type=="kakaotalk")snsShare.kakaoTalk(shareUrl,shareTitle,shareImage,shareDesc)}
function shareFail(){var alertData={title:"alert",content:"카카오톡 공유하기 기능을 실행할 수 없는 환경입니다."};commonAlert(alertData);openLayer("commonAlert")}
function KakaoShare(data){console.log(data);var setting={};if(data.url==null||data.url=="")data.url=document.location.href;if(data.objectType==="feed")setting={objectType:"feed",content:{title:data.title,imageUrl:data.image,link:{mobileWebUrl:data.url,webUrl:data.url}},buttons:[{title:"자세히 보기",link:{mobileWebUrl:data.url,webUrl:data.url}}],installTalk:true,fail:shareFail};if(data.objectType==="location")setting={objectType:"location",address:data.address,addressTitle:data.addressTitle,content:{title:data.title,
imageUrl:"",link:{mobileWebUrl:data.url,webUrl:data.url}},buttons:[{title:"상세 정보",link:{mobileWebUrl:data.url,webUrl:data.url}}]};if(data.objectType==="list")setting={objectType:"list",headerTitle:data.header,headerLink:{webUrl:data.shopUrl,mobileWebUrl:data.shopUrl},contents:data.content};Kakao.Link.sendDefault(setting)};
